var lang = {
	page_name: 'TTSS Kraków',
	page_title: 'TTSS Krak\u00F3w - Odjazdy tramwajów na żywo',
	page_title_stop_name: 'TTSS Krak\u00F3w - $stop - Odjazdy tramwajów na żywo',
	
	jquery_not_loaded: 'Wymagana biblioteka jQuery nie została poprawnie załadowana. Spróbuj odświeżyć stronę.',
	enter_stop_name_to_begin: 'Zacznij wpisywać nazwę przystanku.',
	select_stop_click_go: 'Wyierz przystanek i kliknij "Dalej".',
	stop_name_placeholder: 'Nazwa przystanku',
	go_button: 'Dalej',
	refresh_button: '\u27f3 Odśwież',
	last_refreshed: 'Ostatnio odświeżone $time',
	
	line_alert_pattern: 'Linia $line: $alert',
	
	header_line: 'Linia',
	header_direction: 'Kierunek',
	header_time: 'Odjazd',
	header_delay: 'Opóźnienie',
	header_lines: 'Linie',
	header_route: 'Trasa',
	header_carrier: 'Przewoźnik',
	
	boarding_sign: '>>>',
	unknown_sign: '?',
	
	time_now: 'przed chwilą',
	time_seconds_prefix: '',
	time_seconds_suffix: ' s',
	time_seconds_ago_prefix: '',
	time_seconds_ago_suffix: ' s temu',
	time_minutes_prefix: '',
	time_minutes_suffix: ' min',
	time_minutes_ago_prefix: '',
	time_minutes_ago_suffix: ' min temu',
	
	tram_type_pattern: '$num $type ($floor)',
	high_floor: 'wysokopodłogowy',
	high_floor_sign: '\u2010\u00A0',
	high_floor_description: 'tramwaj wysokopodłogowy',
	partially_low_floor: 'częściowo niskopodłogowy',
	partially_low_floor_sign: '*\u267F',
	partially_low_floor_description: 'tramwaj częściowo niskopodłogowy',
	low_floor: 'niskopodłogowy',
	low_floor_sign: '\u267F',
	low_floor_description: 'tramwaj niskopodłogowy',
	
	status_departed: 'Odjechał',
	status_stopped: 'Na przystanku',
	status_default: 'W trasie',
	status_delayed_4: 'Opóźniony 4′+',
	status_delayed_10: 'Opóźniony 10′+',
	
	help_legend: 'Legenda:',
	help_text: 'Względne czasy (np. 3 min) są podawane na podstawie faktycznej lokalizacji tramwajów. Czasy bezwzględne (np. 8:01) to odjazdy rozkładowe, pokazywane gdy tramwaj nie może być zlokalizowany. "?" oznacza nieznane opóźnienie.',
	help_hover_for_more: 'Najedź na ikonę, by uzyskać więcej informacji.',
	help_source: 'Kod źródłowy',
	help_license: 'Licencja',
	
	error_title: 'Wystąpił błąd!',
	error_request_failed: 'Wykonanie żądania internetowego nie udało się.',
	error_request_failed_status: 'Wykonanie żądania internetowego nie udało się. Błąd: $status.',
	error_request_failed_connectivity: 'Wykonanie żądania internetowego nie udało się - sprawdź połączenie z siecią.',
};
