<?php
$stops = array (
# 't113'  => 'AWF', # nowa nazwa # 't3809' => 'AWF / PK',
  't3809' => 'AWF / PK',
  't462'  => 'Agencja Kraków Wschód',
# 't134'  => 'Balicka Wiadukt', # nowa nazwa # 't136'  => 'Bronowice Wiadukt',
  't449'  => 'Bardosa',
# 't75'   => 'Basztowa LOT', # nowa nazwa # 't3032' => 'Stary Kleparz',
  't78'   => 'Batorego',
  't1271' => 'Białoprądnicka',
  't130'  => 'Białucha',
  't867'  => 'Bieńczycka',
  't630'  => 'Bieżanowska',
  't84'   => 'Biprostal',
  't461'  => 'Blokowa',
  't3730' => 'Bociana',
# 't2798' => 'Boisko Kabel', # dawny tymczasowy
  't747'  => 'Borek Fałęcki',
  't824'  => 'Borek Fałęcki I',
  't612'  => 'Borsucza',
  't451'  => 'Brama nr 4 (nż)',
  't453'  => 'Brama nr 5 (nż)',
  't61'   => 'Bratysławska',
  't89'   => 'Bronowice',
  't135'  => 'Bronowice Małe',
  't3459' => 'Bronowice SKA',
# 't136'  => 'Bronowice Wiadukt', # nowa nazwa # 't3459' => 'Bronowice SKA',
  't613'  => 'Brożka (nż)',
  't409'  => 'Centralna',
# 't3039' => 'Centrum Kongresowe ICE', # nowa nazwa # 't3338' => 'Rondo Grunwaldzkie',
  't2691' => 'Chmieleniec',
  't87'   => 'Cichy Kącik',
  't3037' => 'Cienista',
# 't2549' => 'Cmentarz Grębałów Zachód', # nowa nazwa # 't2685' => 'Jarzębiny',
  't621'  => 'Cmentarz Podgórski',
  't124'  => 'Cmentarz Rakowicki',
# 't318'  => 'Cracovia', # nowa nazwa # 't3141' => 'Muzeum Narodowe',
  't129'  => 'Cystersów',
  't3038' => 'Czerwone Maki P+R',
  't407'  => 'Czyżyny',
  't392'  => 'DH Wanda',
  't915'  => 'Dajwór', # nieczynny - linia muzealna
  't435'  => 'Darwina',
  't632'  => 'Dauna',
  't388'  => 'Dunikowskiego',
  't623'  => 'Dworcowa',
# 't131'  => 'Dworzec Główny', # nowa nazwa # 't3242' => 'Teatr Słowackiego',
  't1173' => 'Dworzec Główny Tunel',
# 't8567' => 'Dworzec Główny Tunel', # duplikat # 't1173' => 'Dworzec Główny Tunel',
  't2608' => 'Dworzec Główny Zachód',
  't2870' => 'Dworzec Płaszów Estakada',
  't70'   => 'Dworzec Towarowy',
# 't6685' => 'Dworzec Towarowy', # duplikat # 't70'   => 'Dworzec Towarowy',
  't370'  => 'Dąbie',
  't464'  => 'Elektromontaż (nż)',
  't368'  => 'Fabryczna',
  't322'  => 'Filharmonia',
  't1051' => 'Fort Mogiła (nż)',
  't367'  => 'Francesco Nullo',
  't3174' => 'Giedroycia (nż)',
  't560'  => 'Gromadzka',
# 't585'  => 'Grota Roweckiego', # nowa nazwa # 't2687' => 'Grota-Roweckiego',
  't2687' => 'Grota-Roweckiego',
  't3785' => 'Górka Narodowa P+R',
  't3662' => 'Górnickiego',
  't1049' => 'Głowackiego',
  't363'  => 'Hala Targowa',
# 't6990' => 'Hala Targowa', # duplikat # 't363'  => 'Hala Targowa',
  't2685' => 'Jarzębiny',
  't452'  => 'Jeżynowa',
  't319'  => 'Jubilat',
  't624'  => 'Kabel',
  't2690' => 'Kampus UJ',
  't576'  => 'Kapelanka',
  't429'  => 'Klasztorna',
  't382'  => 'Kleeberga',
  't946'  => 'Klimeckiego',
  't584'  => 'Kobierzyńska',
# 't401'  => 'Kocmyrzowska', # nowa nazwa # 't3037' => 'Cienista',
  't457'  => 'Koksochemia (nż)',
  't459'  => 'Kombinat',
  't313'  => 'Komorowskiego',
  't450'  => 'Kopiec Wandy',
# 't2536' => 'Kordylewskiego', # nowa nazwa # 't2859' => 'Teatr Variété',
  't571'  => 'Korona',
# 't2803' => 'Kraków Arena Al. Pokoju', # nowa nazwa # 't2871' => 'TAURON Arena Kraków Al. Pokoju',
# 't959'  => 'Kraków Plaza', # nowa nazwa # 't3033' => 'Plaza',
# 't63'   => 'Krowodrza Górka', # nowa nazwa # 't3724' => 'Krowodrza Górka P+R',
# 't7612' => 'Krowodrza Górka', # duplikat # 't63'   => 'Krowodrza Górka',
  't3724' => 'Krowodrza Górka P+R',
  't567'  => 'Kuklińskiego',
# 't744'  => 'Kurdwanów', # nowa nazwa # 't3176' => 'Kurdwanów P+R',
  't3176' => 'Kurdwanów P+R',
# 't7389' => 'Kurdwanów pętla', # nowa nazwa # 't744'  => 'Kurdwanów',
  't3726' => 'Kuźnicy Kołłątajowskiej',
# 't2537' => 'Lema', # nowa nazwa # 't2803' => 'Kraków Arena Al. Pokoju'
  't569'  => 'Limanowskiego',
  't2686' => 'Lipińskiego',
  't561'  => 'Lipska',
  't126'  => 'Lubicz',
# 't930'  => 'M1 Al. Pokoju', # nowa nazwa # 't3472' => 'M1 al. Pokoju',
# 't3472' => 'M1 al. Pokoju', # nowa nazwa # 't3810' => 'Ogród Doświadczeń',
# 't1263' => 'Mały Płaszów', # nowa nazwa # 't3310' => 'Mały Płaszów P+R',
  't3310' => 'Mały Płaszów P+R',
  't454'  => 'Meksyk (nż)',
  't362'  => 'Miodowa',
# 't6989' => 'Miodowa', # duplikat # 't362'  => 'Miodowa',
  't375'  => 'Mistrzejowice',
  't2538' => 'Miśnieńska',
# 't574'  => 'Most Grunwaldzki', # nowa nazwa # 't3039' => 'Centrum Kongresowe ICE',
  't460'  => 'Mrozowa',
  't3621' => 'Muzeum Fotografii',
  't2726' => 'Muzeum Inżynierii Miejskiej', # nieczynny - linia muzealna
# 't2811' => 'Muzeum Lotnictwa', # nowa nazwa # 't3735' => 'Muzeum Lotnictwa Polskiego',
  't3735' => 'Muzeum Lotnictwa Polskiego',
  't3141' => 'Muzeum Narodowe',
  't2688' => 'Norymberska',
# 't372'  => 'Nowohucka', # nowa nazwa # 't3041' => 'Rondo 308. Dywizjonu',
  't715'  => 'Nowosądecka',
# 't2580' => 'Nowy Bieżanów', # nowa nazwa # 't3175' => 'Nowy Bieżanów P+R',
  't3175' => 'Nowy Bieżanów P+R',
  't71'   => 'Nowy Kleparz',
  't2582' => 'Nowy Prokocim',
  't369'  => 'Ofiar Dąbia',
  't3810' => 'Ogród Doświadczeń',
  't823'  => 'Oleandry',
  't361'  => 'Orzeszkowej',
  't413'  => 'Os. Kolorowe',
  't424'  => 'Os. Na Skarpie',
  't378'  => 'Os. Piastów',
  't418'  => 'Os. Zgody',
  't377'  => 'Os. Złotego Wieku',
  't466'  => 'PH',
  't614'  => 'PT',
  't3723' => 'Pachońskiego P+R',
  't3731' => 'Papierni Prądnickich',
  't960'  => 'Park Jordana',
  't716'  => 'Piaski Nowe',
  't379'  => 'Piasta Kołodzieja',
  't570'  => 'Plac Bohaterów Getta',
# 't7207' => 'Plac Bohaterów Getta', # duplikat # 't570'  => 'Plac Bohaterów Getta',
# 't414'  => 'Plac Centralny', # nowa nazwa # 't2744' => 'Plac Centralny im. R.Reagana',
  't2744' => 'Plac Centralny im. R.Reagana',
  't79'   => 'Plac Inwalidów',
  't360'  => 'Plac Wolnica',
  't1360' => 'Plac Wszystkich Świętych',
  't3033' => 'Plaza (nż)',
  't458'  => 'Pleszów',
  't357'  => 'Poczta Główna',
  't3158' => 'Podgórze SKA',
  't73'   => 'Politechnika',
# 't6689' => 'Politechnika', # duplikat # 't73'   => 'Politechnika',
# 't568'  => 'Powstańców Wielkopolskich', # nowa nazwa # 't3158' => 'Podgórze SKA',
# 't7204' => 'Powstańców Wielkopolskich', # duplikat # 't568'  => 'Powstańców Wielkopolskich',
  't637'  => 'Prokocim',
# 't7279' => 'Prokocim', # duplikat # 't637'  => 'Prokocim',
  't682'  => 'Prokocim Szpital',
# 't69'   => 'Prądnicka', # nowa nazwa # 't3036' => 'Szpital Narutowicza',
# 't6684' => 'Prądnicka', # duplikat # 't69'   => 'Prądnicka',
  't72'   => 'Pędzichów',
# 't128'  => 'Rakowicka (nż)', # nowa nazwa # 't3621' => 'Muzeum Fotografii (nż)',
  't320'  => 'Reymana',
  't3041' => 'Rondo 308. Dywizjonu',
  't408'  => 'Rondo Czyżyńskie',
  't3338' => 'Rondo Grunwaldzkie',
  't365'  => 'Rondo Grzegórzeckie',
# 't6992' => 'Rondo Grzegórzeckie', # duplikat # 't365'  => 'Rondo Grzegórzeckie',
  't2539' => 'Rondo Hipokratesa',
# 't419'  => 'Rondo Kocmyrzowskie', # nowa nazwa # 't2745' => 'Rondo Kocmyrzowskie im. Ks. Gorzelanego',
  't2745' => 'Rondo Kocmyrzowskie im. Ks. Gorzelanego',
  't610'  => 'Rondo Matecznego',
  't125'  => 'Rondo Mogilskie',
# 't6747' => 'Rondo Mogilskie', # duplikat # 't125'  => 'Rondo Mogilskie',
  't383'  => 'Rondo Piastowskie',
# 't587'  => 'Rostworowskiego', # nowa nazwa # 't589'  => 'Ruczaj',
  't589'  => 'Ruczaj',
# 't586'  => 'Ruczaj I', # nowa nazwa # 't585'  => 'Grota Roweckiego',
  't1262' => 'Rzebika',
  't611'  => 'Rzemieślnicza',
  't311'  => 'Salwator',
# 't615'  => 'Sanktuarium Bożego Miłosierdzia', # duplikat # 't3646' => 'Sanktuarium Bożego Miłosierdzia',
  't3646' => 'Sanktuarium Bożego Miłosierdzia',
  't33'   => 'Siewna Wiadukt',
  't572'  => 'Smolki',
  't746'  => 'Solvay',
  't358'  => 'Starowiślna',
# 't6985' => 'Starowiślna', # duplikat # 't358'  => 'Starowiślna',
  't3032' => 'Stary Kleparz',
  't112'  => 'Stella-Sawickiego',
  't359'  => 'Stradom',
  't423'  => 'Struga',
  't2548' => 'Suche Stawy',
  't3036' => 'Szpital Narutowicza',
  't575'  => 'Szwedzka',
  't577'  => 'Słomiana',
# 't2871' => 'TAURON Arena Kraków Al. Pokoju (nż)', # nowa nazwa # 't3473' => 'TAURON Arena Kraków al. Pokoju',
  't3473' => 'TAURON Arena Kraków al. Pokoju',
  't3040' => 'TAURON Arena Kraków Wieczysta',
  't77'   => 'Teatr Bagatela',
  't420'  => 'Teatr Ludowy',
  't3242' => 'Teatr Słowackiego',
  't2859' => 'Teatr Variété',
  't681'  => 'Teligi',
  't3647' => 'Turowicza',
  't3736' => 'UJ / AST',
  't3808' => 'UKEN',
  't127'  => 'Uniwersytet Ekonomiczny',
# 't321'  => 'Uniwersytet Jagielloński', # nowa nazwa # 't3736' => 'UJ / AST',
# 't88'   => 'Uniwersytet Pedagogiczny', # nowa nazwa # 't3808' => 'UKEN',
  't83'   => 'Urzędnicza',
  't463'  => 'Walcownia',
  't325'  => 'Wawel',
  't2543' => 'Wańkowicza',
  't133'  => 'Wesele',
  't434'  => 'Wiadukty',
# 't114'  => 'Wieczysta', # nowa nazwa # 't3040' => 'TAURON Arena Kraków Wieczysta',
  't718'  => 'Witosa',
# 't7362' => 'Witosa', # duplikat # 't718'  => 'Witosa',
  't634'  => 'Wlotowa',
  't442'  => 'Wzgórza Krzesławickie',
  't1154' => 'Zabłocie',
  't465'  => 'Zajezdnia Nowa Huta',
  't679'  => 'Ćwiklińskiej',
  't922'  => 'Łagiewniki',
# 't7584' => 'Łagiewniki', # duplikat # 't922'  => 'Łagiewniki',
  't3643' => 'Łagiewniki SKA',
  't2821' => 'Łagiewniki ZUS (nż)',
# 't324'  => 'Św. Gertrudy', # duplikat # 't2741' => 'Św.Gertrudy',
# 't364'  => 'Św. Wawrzyńca', # duplikat # 't2742' => 'Św.Wawrzyńca',
# 't8508' => 'Św. Wawrzyńca', # duplikat # 't364'  => 'Św. Wawrzyńca',
# 't2741' => 'Św. Gertrudy', # nowa nazwa # 't3470' => 'św. Gertrudy',
  't3470' => 'św. Gertrudy',
# 't2742' => 'Św. Wawrzyńca', # nowa nazwa # 't3471' => 'św. Wawrzyńca',
  't3471' => 'św. Wawrzyńca',

  'b3111' => 'AGH / UR',
# 'b113'  => 'AWF', # nowa nazwa # 'b3809' => 'AWF / PK',
  'b3809' => 'AWF / PK',
  'b1328' => 'Agatowa (nż)',
  'b462'  => 'Agencja Kraków Wschód (nż)',
  'b117'  => 'Akacjowa',
  'b2573' => 'Albatrosów',
  'b415'  => 'Aleja Przyjaźni',
  'b416'  => 'Aleja Róż',
  'b2625' => 'Aleja Waszyngtona (nż)',
# 'b235'  => 'Aleksandrowice', # nowa nazwa # 'b3388' => 'Aleksandrowice Centrum',
  'b3388' => 'Aleksandrowice Centrum',
  'b236'  => 'Aleksandrowice Osiedle (nż)',
  'b3150' => 'Aleksandrowicza (nż)',
  'b1122' => 'Aleksandry',
  'b437'  => 'Architektów',
  'b3337' => 'Archiwum UMK (nż)',
  'b403'  => 'Arka',
  'b2533' => 'Armii Krajowej',
  'b54'   => 'Azory',
  'b145'  => 'Baba Jaga (nż)',
  'b767'  => 'Babińskiego',
  'b1083' => 'Baczyńskiego',
  'b2565' => 'Bagienna',
  'b2865' => 'Bagry',
  'b221'  => 'Balice Autostrada (nż)',
  'b2635' => 'Balice Grzybów (nż)',
  'b226'  => 'Balice I (nż)',
# 'b223'  => 'Balice Instytut (nż)', # nowa nazwa # 'b3385' => 'Balice Instytut Zootechniki (nż)',
  'b3385' => 'Balice Instytut Zootechniki (nż)',
  'b3750' => 'Balice Krakowska (nż)',
  'b2636' => 'Balice Leśna (nż)',
  'b3012' => 'Balice Medweckiego (nż)',
# 'b892'  => 'Balice OSP (nż)', # nowa nazwa # 'b3415' => 'Balice Remiza (nż)',
  'b3013' => 'Balice Olszanica Bory',
  'b3415' => 'Balice Remiza (nż)',
  'b222'  => 'Balice Szkoła',
  'b2912' => 'Balice Winna Góra (nż)',
  'b2796' => 'Banacha',
  'b541'  => 'Bartnicza (nż)',
  'b3679' => 'Barwinkowa (nż)',
  'b2551' => 'Barwna (nż)',
  'b703'  => 'Barycz (nż)',
  'b2528' => 'Batalionu \'Skała\' AK',
  'b78'   => 'Batorego',
  'b2962' => 'Batowice Dłubnia',
  'b352'  => 'Batowice Kapliczka',
  'b2959' => 'Batowice Spławy (nż)',
  'b3121' => 'Bazarowa',
  'b578'  => 'Bałuckiego (nż)',
# 'b2633' => 'Belwederczyków (nż)', # nowa nazwa # 'b3785' => 'Górka Narodowa P+R',
  'b2518' => 'Benedyktowicza (nż)',
  'b923'  => 'Beskidzka',
  'b3686' => 'Betonowa',
# 'b1271' => 'Białoprądnicka', # wyłącznie tramwajowy
  'b130'  => 'Białucha',
  'b3549' => 'Biały Kościół Dolina Kluczwody (nż)',
  'b3550' => 'Biały Kościół Murownia (nż)',
  'b3559' => 'Biały Kościół Murownia Pętla',
# 'b973'  => 'Biały Kościół (nż)', # nowa nazwa # 'b3549' => 'Biały Kościół Dolina Kluczwody (nż)',
# 'b330'  => 'Bibice (nż)', # nowa nazwa # 'b3593' => 'Bibice Na Czekaj (nż)',
  'b2783' => 'Bibice Cmentarz (nż)',
  'b2960' => 'Bibice Kościuszki',
  'b3361' => 'Bibice Mokra',
# 'b2995' => 'Bibice Na Czekaj', # nowa nazwa # 'b3361' => 'Bibice Mokra',
  'b3593' => 'Bibice Na Czekaj (nż)',
  'b2961' => 'Bibice Rynek',
  'b260'  => 'Bielany',
  'b262'  => 'Bielany Klasztor (nż)',
  'b3102' => 'Bielany Obwodnica (nż)',
  'b261'  => 'Bielany Szkoła',
  'b265'  => 'Bielańska (nż)',
  'b272'  => 'Bielańskie Skały (nż)',
  'b867'  => 'Bieńczycka',
  'b630'  => 'Bieżanowska',
  'b667'  => 'Bieżanów',
  'b3183' => 'Bieżanów Drożdżownia SKA',
  'b2725' => 'Bieżanów Granica Miasta',
  'b672'  => 'Bieżanów Kaim',
  'b665'  => 'Bieżanów Pomnik',
  'b670'  => 'Bieżanów Potrzask',
  'b663'  => 'Bieżanów Szkoła',
  'b662'  => 'Bieżanów Trafo',
  'b84'   => 'Biprostal',
  'b122'  => 'Biskupa Prandoty',
# 'b3244' => 'Biskupia', # tymczasowy - przebudowa linii do Bronowic
# 'b3220' => 'Biskupice I (nż)', # nowa nazwa # 'b3803' => 'Biskupice Rymarówka (nż)',
# 'b3221' => 'Biskupice II (nż)', # nowa nazwa # 'b3804' => 'Biskupice Szczygłów (nż)',
  'b3803' => 'Biskupice Rymarówka (nż)',
  'b3804' => 'Biskupice Szczygłów (nż)',
  'b2574' => 'Biskupińska (nż)',
  'b461'  => 'Blokowa (nż)',
  'b2597' => 'Bochenka (nż)',
# 'b34'   => 'Bociana', # nowa nazwa # 'b3721' => 'Zawodzie',
  'b3730' => 'Bociana',
  'b3737' => 'Bodzowska',
  'b3738' => 'Bodzów',
# 'b3381' => 'Bodzów', # nowa nazwa # 'b3737' => 'Bodzowska',
  'b592'  => 'Bogucianka',
  'b1258' => 'Bojki',
# 'b208'  => 'Bolechowice', # nowa nazwa # 'b3413' => 'Bolechowice Centrum',
  'b3413' => 'Bolechowice Centrum',
  'b2917' => 'Bolechowice Drogi (nż)',
  'b2916' => 'Bolechowice Krzewiny (nż)',
  'b2915' => 'Bolechowice Zielona (nż)',
  'b2920' => 'Bolechowice Zielona Mała (nż)',
  'b2561' => 'Bolesława Śmiałego',
  'b3210' => 'Boleń Pętla',
  'b1255' => 'Bonarka',
  'b810'  => 'Bora-Komorowskiego',
  'b747'  => 'Borek Fałęcki',
  'b3540' => 'Borek Szlachecki (nż)',
# 'b1118' => 'Borek Szlachecki I (nż)', # nowa nazwa # 'b3540' => 'Borek Szlachecki (nż)',
# 'b1117' => 'Borek Szlachecki II (nż)', # nowa nazwa # 'b3539' => 'Borek Szlachecki Kościół (nż)',
  'b3539' => 'Borek Szlachecki Kościół (nż)',
  'b753'  => 'Borkowska',
  'b612'  => 'Borsucza',
  'b2532' => 'Bosaków',
# 'b1071' => 'Bosutów Dziekanowice (nż)', # nowa nazwa # 'b3442' => 'Węgrzce B1 (nż)',
  'b3706' => 'Bosutów Kościuszki',
  'b2769' => 'Bosutów Krakowska (nż)',
# 'b3211' => 'Bosutów Remiza', # nowa nazwa # 'b3706' => 'Bosutów Kościuszki',
  'b453'  => 'Brama nr 5 (nż)',
  'b3680' => 'Brama nr 8 (nż)',
  'b530'  => 'Branice (nż)',
# 'b513'  => 'Branice Na Dole (nż)', # nowa nazwa # 'b3682' => 'Deszczowa (nż)',
  'b2652' => 'Branice Ośrodek Zdrowia (nż)',
# 'b512'  => 'Branice Pagórek (nż)', # nowa nazwa # 'b3681' => 'Plastusia (nż)',
  'b531'  => 'Branice Szkoła',
  'b61'   => 'Bratysławska',
  'b1165' => 'Brodowicza',
  'b123'  => 'Brogi',
  'b89'   => 'Bronowice',
  'b135'  => 'Bronowice Małe',
  'b3459' => 'Bronowice SKA',
# 'b136'  => 'Bronowice Wiadukt', # nowa nazwa # 'b3459' => 'Bronowice SKA',
  'b19'   => 'Bronowice Wielkie',
# 'b638'  => 'Brzegi', # nowa nazwa # 'b3311' => 'Brzegi Pętla',
  'b3510' => 'Brzegi Dom Kultury (nż)',
  'b3511' => 'Brzegi Granica (nż)',
  'b3509' => 'Brzegi Grobla',
# 'b639'  => 'Brzegi I', # nowa nazwa # 'b3509' => 'Brzegi Grobla',
# 'b1294' => 'Brzegi III (nż)', # nowa nazwa # 'b3510' => 'Brzegi Dom Kultury (nż)',
  'b3311' => 'Brzegi Pętla',
  'b3340' => 'Brzegi Użytek Ekologiczny (nż)',
# 'b2648' => 'Brzeska (nż)', # nowa nazwa # 'b3691' => 'Szlifierska (nż)',
  'b1016' => 'Brzezie Działki (nż)',
  'b3209' => 'Brzezie Kluczwody (nż)',
  'b3049' => 'Brzezie Kościół (nż)',
  'b1048' => 'Brzezie Kulka (nż)',
  'b1021' => 'Brzezie Narodowe (nż)',
# 'b1028' => 'Brzezinka', # nowa nazwa # 'b3417' => 'Brzezinka Kościół',
  'b3417' => 'Brzezinka Kościół',
  'b3329' => 'Brzezinka Kuźnia (nż)',
  'b1029' => 'Brzezinka Skrzyżowanie',
  'b1027' => 'Brzezinka Zarzecze (nż)',
# 'b1106' => 'Brzeźnica', # nowa nazwa # 'b3328' => 'Brzeźnica Dworzec',
  'b3328' => 'Brzeźnica Dworzec',
# 'b1109' => 'Brzeźnica Kuźnia (nż)', # nowa nazwa # 'b3329' => 'Brzezinka Kuźnia (nż)',
  'b1108' => 'Brzeźnica Pasieka (nż)',
  'b2695' => 'Brzoskwinia Góra (nż)',
  'b240'  => 'Brzoskwinia Kamyk (nż)',
  'b238'  => 'Brzoskwinia Koziary (nż)',
  'b3201' => 'Brzoskwinia Pętla',
  'b3521' => 'Brzoskwinia Remiza',
# 'b239'  => 'Brzoskwinia Sklep', # nowa nazwa # 'b3521' => 'Brzoskwinia Remiza',
  'b3271' => 'Brzozówka Oskarówka',
  'b3272' => 'Brzozówka Ośrodek',
  'b2708' => 'Brzyczyna',
  'b765'  => 'Brücknera',
  'b2780' => 'Budzyń Plaża Główna (nż)',
# 'b2781' => 'Budzyń Zalew Budzyński (nż)', # nowa nazwa # 'b3464' => 'Cholerzyn Chałupki (nż)',
  'b2779' => 'Budzyń Zalew na Piaskach (nż)',
  'b743'  => 'Bujaka',
# 'b881'  => 'Buków', # nowa nazwa # 'b3323' => 'Buków Pętla',
  'b882'  => 'Buków Klin (nż)',
  'b3323' => 'Buków Pętla',
  'b883'  => 'Buków Szkoła (nż)',
  'b432'  => 'Bulwarowa (nż)',
  'b2603' => 'Bulwarowa Ogródki Działkowe (nż)',
  'b1346' => 'Bunscha',
# 'b2914' => 'Burów (nż)', # nowa nazwa # 'b3414' => 'Burów Balica (nż)',
  'b3414' => 'Burów Balica (nż)',
  'b2913' => 'Burów Centrum',
  'b2627' => 'Bystronia (nż)',
  'b978'  => 'Bębło Lasek (nż)',
  'b976'  => 'Bębło Stara Wieś (nż)',
  'b977'  => 'Bębło Łabajowa (nż)',
# 'b982'  => 'Będkowice', # nowa nazwa # 'b3551' => 'Będkowice Rynek',
  'b981'  => 'Będkowice Borynia (nż)',
  'b3007' => 'Będkowice Cmentarz (nż)',
  'b2869' => 'Będkowice Długa (nż)',
  'b980'  => 'Będkowice Kawiory (nż)',
  'b979'  => 'Będkowice Mosurowa (nż)',
  'b2700' => 'Będkowice Pętla',
  'b3551' => 'Będkowice Rynek',
  'b505'  => 'Błonia Kościelnickie (nż)',
  'b2595' => 'Cechowa (nż)',
  'b385'  => 'Cedyńska',
  'b409'  => 'Centralna',
  'b2453' => 'Centrum JP II',
# 'b3039' => 'Centrum Kongresowe ICE', # nowa nazwa # 'b3338' => 'Rondo Grunwaldzkie',
  'b40'   => 'Chabrowa',
  'b728'  => 'Chałubińskiego (nż)',
  'b525'  => 'Chałupki',
  'b2651' => 'Chałupki Górne (nż)',
  'b151'  => 'Chełm',
  'b3073' => 'Chełmońskiego Osiedle',
  'b3072' => 'Chełmońskiego Pętla',
  'b152'  => 'Chełmska (nż)',
  'b2691' => 'Chmieleniec',
  'b1274' => 'Chobot (nż)',
  'b1288' => 'Chobot Leśniczówka',
# 'b254'  => 'Cholerzyn (nż)', # nowa nazwa # 'b3298' => 'Cholerzyn Skwer (nż)',
  'b3464' => 'Cholerzyn Chałupki (nż)',
  'b3056' => 'Cholerzyn Granica (nż)',
  'b253'  => 'Cholerzyn Sklep (nż)',
  'b252'  => 'Cholerzyn Skrzyżowanie (nż)',
  'b3298' => 'Cholerzyn Skwer (nż)',
  'b3055' => 'Cholerzyn Zagórze (nż)',
  'b2878' => 'Chopina',
# 'b886'  => 'Chorowice', # nowa nazwa # 'b3324' => 'Chorowice Pętla',
  'b3324' => 'Chorowice Pętla',
  'b3500' => 'Chorzowska (nż)',
  'b230'  => 'Chrosna Kapliczka (nż)',
  'b2911' => 'Chrosna Pętla',
  'b229'  => 'Chrosna Sklep (nż)',
  'b228'  => 'Chrosna Studnia (nż)',
  'b3743' => 'Cianowice Duże (nż)',
  'b3745' => 'Cianowice Małe (nż)',
  'b3742' => 'Cianowice Poręba (nż)',
  'b3744' => 'Cianowice Szczodrkowice (nż)',
  'b87'   => 'Cichy Kącik',
  'b2653' => 'Ciekowiec (nż)',
  'b3037' => 'Cienista',
  'b36'   => 'Clepardia',
# 'b897'  => 'Cmentarz Batowice', # nowa nazwa # 'b3658' => 'Cmentarz Prądnik Czerwony',
# 'b2699' => 'Cmentarz Batowice Wschód (nż)', # nowa nazwa # 'b3659' => 'Cmentarz Prądnik Czerwony Wschód (nż)',
  'b3137' => 'Cmentarz Bielany (nż)',
  'b3126' => 'Cmentarz Bieżanów',
  'b3139' => 'Cmentarz Borek Fałęcki (nż)',
  'b3108' => 'Cmentarz Bronowice (nż)',
  'b448'  => 'Cmentarz Grębałów',
  'b2989' => 'Cmentarz Grębałów Południe (nż)',
  'b3565' => 'Cmentarz Mydlniki (nż)',
  'b3034' => 'Cmentarz Olszanica (nż)',
  'b3689' => 'Cmentarz Pleszów (nż)',
  'b621'  => 'Cmentarz Podgórski',
  'b2992' => 'Cmentarz Prokocim',
  'b3658' => 'Cmentarz Prądnik Czerwony',
  'b3659' => 'Cmentarz Prądnik Czerwony Wschód (nż)',
  'b124'  => 'Cmentarz Rakowicki',
  'b2531' => 'Cmentarz Rakowicki Zachód (nż)',
  'b3120' => 'Cmentarz Ruszcza (nż)',
  'b3133' => 'Cmentarz Wróblowice',
  'b822'  => 'Conrada',
  'b2500' => 'Cracovia Błonia',
  'b2501' => 'Cracovia Stadion',
  'b129'  => 'Cystersów',
# 'b975'  => 'Czajowice (nż)', # nowa nazwa # 'b3773' => 'Czajowice Władysława Łokietka (nż)',
  'b3773' => 'Czajowice Władysława Łokietka (nż)',
# 'b1159' => 'Czarnochowice I (nż)', # nowa nazwa # 'b3578' => 'Czarnochowice Kokotowska (nż)',
  'b3578' => 'Czarnochowice Kokotowska (nż)',
  'b81'   => 'Czarnowiejska',
  'b3684' => 'Czeczeńska (nż)',
  'b1226' => 'Czernichów Bór (nż)',
# 'b1204' => 'Czernichów GS (nż)', # nowa nazwa # 'b3402' => 'Czernichów Studzienki (nż)',
# 'b3224' => 'Czernichów Pętla', # nowa nazwa # 'b3394' => 'Czernichów Rynek',
  'b2892' => 'Czernichów Ratanice (nż)',
  'b2891' => 'Czernichów Ratanice Most (nż)',
  'b3394' => 'Czernichów Rynek',
  'b1203' => 'Czernichów Stacja Paliw (nż)',
  'b3402' => 'Czernichów Studzienki (nż)',
  'b2890' => 'Czernichów Zakamycze (nż)',
  'b920'  => 'Czerwiakowskiego',
  'b1063' => 'Czerwieńskiego',
  'b3038' => 'Czerwone Maki P+R',
# 'b878'  => 'Czulice', # nowa nazwa # 'b3283' => 'Czulice Kościół',
# 'b496'  => 'Czulice I (nż)', # nowa nazwa # 'b3280' => 'Czulice Przymiarki (nż)',
  'b3283' => 'Czulice Kościół',
  'b3280' => 'Czulice Przymiarki (nż)',
# 'b2881' => 'Czułów (nż)', # nowa nazwa # 'b3295' => 'Czułów Granica (nż)',
# 'b2880' => 'Czułów Droga na Czułówek (nż)', # nowa nazwa # 'b3294' => 'Czułów Sklep (nż)',
  'b3295' => 'Czułów Granica (nż)',
  'b3294' => 'Czułów Sklep (nż)',
  'b2879' => 'Czułów Szkoła',
  'b1215' => 'Czułówek (nż)',
  'b1365' => 'Czułówek Kapliczka',
  'b407'  => 'Czyżyny',
  'b965'  => 'Czyżyny Dworzec',
  'b522'  => 'Cło',
  'b392'  => 'DH Wanda',
  'b3122' => 'Danalówka (nż)',
  'b435'  => 'Darwina',
  'b632'  => 'Dauna',
  'b3682' => 'Deszczowa (nż)',
  'b3113' => 'Dobrego Pasterza',
# 'b3370' => 'Dobry Początek (nż)', # tymczasowy - przebudowa ul. Wrobela
  'b474'  => 'Dojazdów Działki (nż)',
  'b3718' => 'Dojazdów Na Górce (nż)',
  'b475'  => 'Dojazdów PKS',
  'b3719' => 'Dojazdów Plac św. Stanisława (nż)',
  'b3717' => 'Dojazdów Przedszkole (nż)',
# 'b686'  => 'Dom Spokojnej Starości', # nowa nazwa # 'b3384' => 'Miejskie Centrum Opieki',
  'b3732' => 'Dom Zwierzyniecki',
  'b646'  => 'Domagały (nż)',
  'b3412' => 'Domagały Magazyny (nż)',
  'b31'   => 'Dożynkowa',
# 'b216'  => 'Droga do Niegoszowic (nż)', # nowa nazwa # 'b3519' => 'Kochanów Sowiarka (nż)',
# 'b192'  => 'Droga do Rząski (nż)', # nowa nazwa # 'b2990' => 'Rząska Cmentarz (nż)',
  'b2614' => 'Drożdżowa',
  'b518'  => 'Drożyska (nż)',
  'b2590' => 'Drużbackiej',
# 'b2922' => 'Dubie Skrzyżowanie (nż)', # nowa nazwa # 'b3531' => 'Pisary Dąbrówki (nż)',
  'b388'  => 'Dunikowskiego',
  'b3125' => 'Duża Góra (nż)',
  'b623'  => 'Dworcowa',
  'b1060' => 'Dworzec Główny Wschód',
  'b2608' => 'Dworzec Główny Zachód',
  'b836'  => 'Dwór Czeczów',
  'b2657' => 'Dymarek (nż)',
  'b3193' => 'Dziekanowice Batowice SKA',
  'b3165' => 'Dziekanowice Długa (nż)',
  'b3166' => 'Dziekanowice Kapliczka',
  'b3194' => 'Dziekanowicka (nż)',
  'b370'  => 'Dąbie',
  'b600'  => 'Dąbrowa',
# 'b1202' => 'Dąbrowa Szlachecka (nż)', # nowa nazwa # 'b3401' => 'Wołowice Skrzyżowanie (nż)',
  'b907'  => 'Dąbrowa Szlachecka Figurka (nż)',
  'b1237' => 'Dąbrowa Szlachecka Krzemiennik',
  'b910'  => 'Dąbrowa Szlachecka Krzyż (nż)',
  'b3117' => 'Dąbrowskiej',
  'b838'  => 'EC Łęg',
  'b374'  => 'Elektrociepłownia Kraków',
  'b464'  => 'Elektromontaż (nż)',
  'b3536' => 'Facimiech Pod Kolebą (nż)',
  'b3116' => 'Fatimska (nż)',
  'b322'  => 'Filharmonia',
  'b1375' => 'Fiszera',
  'b3782' => 'Folwarczna (nż)',
  'b2566' => 'Fort Bodzów (nż)',
  'b1051' => 'Fort Mogiła',
  'b3774' => 'Fort Skotniki',
  'b2587' => 'Fort Swoszowice (nż)',
  'b1371' => 'Fort Winnica (nż)',
  'b754'  => 'Forteczna',
  'b367'  => 'Francesco Nullo',
  'b617'  => 'Fredry',
  'b3534' => 'Friedleina',
  'b2615' => 'Gaik (nż)',
  'b2856' => 'Gaj Kwiatowa (nż)',
  'b2857' => 'Gaj Rudawa (nż)',
  'b790'  => 'Gaj Szkoła',
  'b791'  => 'Gaj Zadziele',
  'b2858' => 'Gaj Zgody (nż)',
# 'b174'  => 'Garlica Duchowna (nż)', # nowa nazwa # 'b3344' => 'Garlica Duchowna Kapliczka (nż)',
# 'b2957' => 'Garlica Duchowna Droga do Garliczki', # nowa nazwa # 'b2628' => 'Garlica Duchowna Rozjazd',
  'b3344' => 'Garlica Duchowna Kapliczka (nż)',
  'b2628' => 'Garlica Duchowna Rozjazd',
# 'b175'  => 'Garlica Murowana', # nowa nazwa # 'b3345' => 'Garlica Murowana Plac Zabaw',
  'b2770' => 'Garlica Murowana Kasztany (nż)',
  'b3345' => 'Garlica Murowana Plac Zabaw',
# 'b2958' => 'Garlica Murowana Podskale (nż)', # nowa nazwa # 'b3358' => 'Zielonki Jaskinia Zielonkowska (nż)',
  'b2629' => 'Garliczka Chochół (nż)',
  'b2588' => 'Geologów (nż)',
# 'b1172' => 'Giebułtów', # nowa nazwa # 'b3497' => 'Giebułtów Kościół',
  'b3497' => 'Giebułtów Kościół',
  'b1177' => 'Giebułtów Morgi',
  'b3494' => 'Giebułtów Osiedle Polana (nż)',
  'b1176' => 'Giebułtów Plac Zabaw (nż)',
# 'b2877' => 'Giebułtów Trojadyn (nż)', # nowa nazwa # 'b3495' => 'Giebułtów Zielone Wzgórze (nż)',
# 'b2876' => 'Giebułtów Trojadyn Trafo (nż)', # nowa nazwa # 'b3494' => 'Giebułtów Osiedle Polana (nż)',
  'b1352' => 'Giebułtów Zbiornik (nż)',
  'b3495' => 'Giebułtów Zielone Wzgórze (nż)',
  'b3496' => 'Giebułtów Świętego Idziego (nż)',
  'b3174' => 'Giedroycia (nż)',
  'b3178' => 'Giedroycia ZTPO (nż)',
  'b3588' => 'Giełda Balicka (nż)',
# 'b2766' => 'Giełda Balicka P+R (nż)', # nowa nazwa # 'b3588' => 'Giełda Balicka (nż)',
  'b276'  => 'Glinnik (nż)',
  'b2751' => 'Glogera (nż)',
  'b2752' => 'Glogera Granica Miasta (nż)',
  'b2993' => 'Gnieźnieńska (nż)',
  'b2909' => 'Godlewskiego',
  'b3705' => 'Golkowice Granica (nż)',
  'b3059' => 'Golkowice Kościół',
  'b3146' => 'Golkowice Pętla',
  'b3144' => 'Golkowice Sklep',
  'b22'   => 'Gospodarska',
# 'b2760' => 'Goszcza', # nowa nazwa # 'b3289' => 'Goszcza Dworek',
  'b2763' => 'Goszcza Cmentarz (nż)',
  'b3289' => 'Goszcza Dworek',
# 'b955'  => 'Goszyce (nż)', # nowa nazwa # 'b3291' => 'Goszyce Pod Lasem (nż)',
  'b3291' => 'Goszyce Pod Lasem (nż)',
  'b954'  => 'Goszyce Remiza (nż)',
  'b3766' => 'Gotkowice Wieś (nż)',
  'b1090' => 'Gołuchowice',
  'b1091' => 'Gołuchowice Jurczyce',
  'b1092' => 'Gołuchowice Sklep (nż)',
# 'b2493' => 'Grabie', # nowa nazwa # 'b3333' => 'Grabie Pętla',
  'b1293' => 'Grabie Dom Kultury (nż)',
  'b1295' => 'Grabie Kościół',
  'b2492' => 'Grabie Kuźnia (nż)',
  'b1094' => 'Grabie Polanka (nż)',
  'b3333' => 'Grabie Pętla',
  'b1292' => 'Grabie Szczurów (nż)',
  'b3339' => 'Grabowa',
  'b3145' => 'Grabówki Pętla',
  'b560'  => 'Gromadzka',
  'b2687' => 'Grota-Roweckiego',
# 'b76'   => 'Grottgera', # nowa nazwa # 'b3638' => 'Radio Kraków',
  'b3186' => 'Grzegorza z Sanoka (nż)',
  'b3781' => 'Grębałów',
# 'b443'  => 'Grębałów (nż)', # nowa nazwa # 'b3775' => 'Jubileuszowa (nż)',
# 'b2974' => 'Grębynice (nż)', # nowa nazwa # 'b3457' => 'Grębynice Parkowa (nż)',
  'b1150' => 'Grębynice Mogiełki (nż)',
# 'b2973' => 'Grębynice OSP (nż)', # nowa nazwa # 'b2973' => 'Grębynice OSP (nż)',
  'b3457' => 'Grębynice Parkowa (nż)',
  'b3456' => 'Grębynice Remiza (nż)',
  'b455'  => 'Gwarecka (nż)',
  'b749'  => 'Góra Borkowska (nż)',
# 'b35'   => 'Górka Narodowa', # nowa nazwa # 'b3722' => 'Prądnik Biały Wschód',
  'b3785' => 'Górka Narodowa P+R',
# 'b2797' => 'Górka Narodowa Wschód', # nowa nazwa # 'b3727' => 'Os. Gotyk',
  'b2567' => 'Górka Pychowicka (nż)',
# 'b170'  => 'Górna Wieś', # nowa nazwa # 'b3342' => 'Górna Wieś Pętla',
  'b3342' => 'Górna Wieś Pętla',
  'b1049' => 'Głowackiego',
# 'b876'  => 'Głęboka', # nowa nazwa # 'b3281' => 'Głęboka Staw',
  'b2996' => 'Głęboka Kolonia (nż)',
  'b3281' => 'Głęboka Staw',
  'b3046' => 'Głęboka Zakręt (nż)',
  'b552'  => 'Habina (nż)',
  'b2991' => 'Hala Sportowa Piaski Wielkie (nż)',
  'b363'  => 'Hala Targowa',
  'b2583' => 'Hallera (nż)',
  'b741'  => 'Halszki',
  'b2642' => 'Hektary (nż)',
# 'b931'  => 'Herberta (nż)', # nieczynny
# 'b315'  => 'Hofmana', # nowa nazwa # 'b3466' => 'Piastowska',
  'b3157' => 'Husarska (nż)',
# 'b510'  => 'Igołomska (nż)', # nowa nazwa # 'b3679' => 'Barwinkowa (nż)',
  'b3676' => 'Igołomska Zakłady (nż)',
  'b38'   => 'Imbramowska',
# 'b685'  => 'Instytut Pediatrii', # nowa nazwa # 'b3383' => 'Szpital Uniwersytecki / Instytut Pediatrii',
  'b317'  => 'Instytut Reumatologii',
  'b840'  => 'Isep (nż)',
# 'b933'  => 'Iwanowice', # nowa nazwa # 'b3353' => 'Iwanowice Dworskie Pętla',
  'b3642' => 'Iwanowice Dworskie Kotryska (nż)',
  'b3353' => 'Iwanowice Dworskie Pętla',
# 'b3243' => 'Jadwigi z Łobzowa', # tymczasowy - przebudowa linii do Bronowic
  'b2626' => 'Jana Kazimierza',
  'b1062' => 'Janasówka (nż)',
  'b185'  => 'Januszowice',
  'b3709' => 'Januszowice Młyńska (nż)',
  'b506'  => 'Janówka (nż)',
  'b668'  => 'Jasieńskiego (nż)',
  'b832'  => 'Jasnogórska (nż)',
# 'b1110' => 'Jaśkowice (nż)', # nowa nazwa # 'b3535' => 'Jaśkowice Remiza (nż)',
  'b1111' => 'Jaśkowice PKP (nż)',
  'b3535' => 'Jaśkowice Remiza (nż)',
  'b3764' => 'Jerzmanowice Centralna (nż)',
  'b3763' => 'Jerzmanowice Lepianka (nż)',
  'b3765' => 'Jerzmanowice Ojcowska (nż)',
  'b3762' => 'Jerzmanowice Pod Lasem (nż)',
  'b2586' => 'Jerzmanowskiego',
  'b3228' => 'Jeziorzany Górskie Domy (nż)',
  'b2904' => 'Jeziorzany Pętla',
  'b2903' => 'Jeziorzany Rondo (nż)',
  'b655'  => 'Jeżowa',
  'b2617' => 'Jordanowska (nż)',
  'b319'  => 'Jubilat',
  'b3775' => 'Jubileuszowa (nż)',
  'b758'  => 'Judyma',
  'b2792' => 'Judyma Szkoła',
  'b742'  => 'Jugowicka',
  'b3190' => 'Jurczaka (nż)',
  'b2488' => 'Jurczyce Dom Ludowy',
  'b2490' => 'Jurczyce Podole (nż)',
  'b2489' => 'Jurczyce Szkoła (nż)',
  'b3234' => 'Jędrzejczyka (nż)',
  'b624'  => 'Kabel',
# 'b1222' => 'Kamień Dół (nż)', # nowa nazwa # 'b3404' => 'Kamień Remiza (nż)',
  'b3404' => 'Kamień Remiza (nż)',
  'b3279' => 'Kamień Szkoła',
  'b620'  => 'Kamieńskiego',
  'b619'  => 'Kamieńskiego Wiadukt (nż)',
  'b2690' => 'Kampus UJ',
  'b445'  => 'Kantorowice',
  'b3780' => 'Kantorowicka (nż)',
  'b576'  => 'Kapelanka',
  'b3206' => 'Karniowice Górki (nż)',
  'b3205' => 'Karniowice Pętla',
# 'b877'  => 'Karniów', # nowa nazwa # 'b3282' => 'Karniów Szkoła',
  'b3282' => 'Karniów Szkoła',
  'b546'  => 'Karowa (nż)',
  'b717'  => 'Karpińskiego',
  'b147'  => 'Kasztanowa',
  'b283'  => 'Kaszów',
  'b282'  => 'Kaszów II (nż)',
  'b3483' => 'Kaszów Na Górce (nż)',
  'b3303' => 'Kaszów Szkoła nr 2 (nż)',
  'b284'  => 'Kaszów Tyrałówka (nż)',
  'b3304' => 'Kaszów Wielka Droga (nż)',
  'b2886' => 'Kaszów Wyźrał (nż)',
  'b285'  => 'Kaszów Łysa Góra (nż)',
  'b13'   => 'Katowicka',
  'b82'   => 'Kawiory',
  'b945'  => 'Kenara (nż)',
  'b427'  => 'Klasztor Cystersów',
  'b429'  => 'Klasztorna',
  'b382'  => 'Kleeberga',
# 'b1054' => 'Kleszczów', # nowa nazwa # 'b3423' => 'Kleszczów Centrum',
  'b3423' => 'Kleszczów Centrum',
  'b2864' => 'Kleszczów Pod Lipką (nż)',
  'b946'  => 'Klimeckiego',
  'b3498' => 'Kliny Poranne',
  'b935'  => 'Kliny Zacisze',
  'b768'  => 'Kobierzyn',
  'b584'  => 'Kobierzyńska',
  'b3207' => 'Kobylany Dworska (nż)',
  'b3204' => 'Kobylany Kwiatowa',
  'b1065' => 'Kobylany Remiza (nż)',
# 'b215'  => 'Kochanów', # nowa nazwa # 'b3518' => 'Kochanów Centrum',
  'b3518' => 'Kochanów Centrum',
# 'b214'  => 'Kochanów I (nż)', # nowa nazwa # 'b3517' => 'Zabierzów Wrzosowa (nż)',
  'b3519' => 'Kochanów Sowiarka (nż)',
# 'b3042' => 'Kocmyrzów', # nowa nazwa # 'b3292' => 'Kocmyrzów-Luborzyca Urząd Gminy',
  'b3001' => 'Kocmyrzów Biblioteka',
  'b1257' => 'Kocmyrzów Krzyżówka (nż)',
  'b3000' => 'Kocmyrzów Rondo',
  'b3005' => 'Kocmyrzów Sodfiny (nż)',
  'b3292' => 'Kocmyrzów-Luborzyca Urząd Gminy',
  'b1158' => 'Kokotów I (nż)',
  'b1162' => 'Kokotów II (nż)',
  'b457'  => 'Koksochemia (nż)',
  'b2563' => 'Kolna (nż)',
  'b459'  => 'Kombinat',
  'b313'  => 'Komorowskiego',
  'b830'  => 'Komuny Paryskiej',
# 'b799'  => 'Konary', # nowa nazwa # 'b3364' => 'Konary Pętla',
  'b3312' => 'Konary Królowej Polski (nż)',
  'b3052' => 'Konary Pod Sosenką (nż)',
  'b3364' => 'Konary Pętla',
  'b1347' => 'Konary Sęk (nż)',
# 'b805'  => 'Konary Włosań (nż)', # nowa nazwa # 'b3312' => 'Konary Królowej Polski (nż)',
  'b3673' => 'Konopczyńskiego',
  'b326'  => 'Konopnickiej',
  'b148'  => 'Kopalina (nż)',
  'b2932' => 'Kopanka Druga (nż)',
  'b2484' => 'Kopanka Kapliczka (nż)',
  'b2813' => 'Kopanka Kościół (nż)',
  'b3451' => 'Kopanka Ofiar Katynia',
  'b2931' => 'Kopanka Pętla',
  'b2485' => 'Kopanka Szkoła',
  'b242'  => 'Kopiec Kościuszki',
  'b3581' => 'Korepty (nż)',
  'b571'  => 'Korona',
  'b2970' => 'Korzkiew Botoja (nż)',
  'b2971' => 'Korzkiew Zamek (nż)',
  'b156'  => 'Kosmowskiej (nż)',
  'b706'  => 'Kosocice',
  'b2585' => 'Kosocicka (nż)',
  'b601'  => 'Kostrze',
  'b597'  => 'Kostrze Kapliczka (nż)',
  'b599'  => 'Kostrze OSP',
  'b605'  => 'Kostrze Szkoła',
  'b2559' => 'Koszykarska',
  'b3063' => 'Kozienicka',
# 'b342'  => 'Kozierów Skrzyżowanie (nż)', # nowa nazwa # 'b3348' => 'Narama Graniczna Sklep (nż)',
  'b1139' => 'Kończyce',
  'b3656' => 'Kończyce Rycerza Racibora (nż)',
  'b2644' => 'Kościelniki',
  'b2861' => 'Kraków Airport',
# 'b2975' => 'Krasieniec Pod Lipą', # nowa nazwa # 'b3359' => 'Krasieniec Zakupny Pod Lipą',
# 'b346'  => 'Krasieniec Remiza (nż)', # nowa nazwa # 'b3352' => 'Krasieniec Zakupny Remiza (nż)',
# 'b345'  => 'Krasieniec Stary (nż)', # nowa nazwa # 'b3351' => 'Krasieniec Stary Kopalina (nż)',
  'b3351' => 'Krasieniec Stary Kopalina (nż)',
  'b3350' => 'Krasieniec Stary Skrzyżowanie (nż)',
# 'b934'  => 'Krasieniec Zakupny', # nowa nazwa # 'b3354' => 'Krasieniec Zakupny Kapliczka',
  'b3354' => 'Krasieniec Zakupny Kapliczka',
  'b3641' => 'Krasieniec Zakupny Kotryska (nż)',
  'b3359' => 'Krasieniec Zakupny Pod Lipą',
  'b3352' => 'Krasieniec Zakupny Remiza (nż)',
  'b998'  => 'Krasnowolskiego (nż)',
  'b3654' => 'Krokusowa (nż)',
  'b62'   => 'Krowoderskich Zuchów',
# 'b63'   => 'Krowodrza Górka', # nowa nazwa # 'b3724' => 'Krowodrza Górka P+R',
  'b3724' => 'Krowodrza Górka P+R',
  'b2601' => 'Krowodrza Urzędy Skarbowe',
  'b381'  => 'Kruszwicka',
  'b258'  => 'Kryspinów',
  'b257'  => 'Kryspinów Sanka (nż)',
# 'b2895' => 'Kryspinów Stopień Wodny (nż)', # nowa nazwa # 'b3371' => 'Kryspinów Stopień Wodny (nż)',
  'b3371' => 'Kryspinów Stopień Wodny (nż)',
  'b702'  => 'Krzemieniecka (nż)',
  'b3250' => 'Krzeszowice Dworzec Autobusowy',
  'b2923' => 'Krzeszowice Krakowska Muzeum (nż)',
  'b3525' => 'Krzeszowice Wiadukt (nż)',
# 'b1044' => 'Krzeszowice Witaminka (nż)', # nowa nazwa # 'b3525' => 'Krzeszowice Wiadukt (nż)',
  'b3134' => 'Krzesławice Młyn (nż)',
  'b1192' => 'Krzyszkowice Kasztanowa I (nż)',
  'b1193' => 'Krzyszkowice Kasztanowa II (nż)',
# 'b1191' => 'Krzyszkowice Kościół (nż)', # nowa nazwa # 'b3650' => 'Wieliczka Krzyszkowice Kościół (nż)',
# 'b2817' => 'Krzyszkowice Krzyszkowicka', # nowa nazwa # 'b3653' => 'Wieliczka Krzyszkowice Dom Ludowy',
# 'b1194' => 'Krzyszkowice Modrzewiowa (nż)', # nowa nazwa # 'b3651' => 'Wieliczka Modrzewiowa (nż)',
# 'b2740' => 'Krzyszkowice Os.Szymanowskiego (nż)', # nowa nazwa # 'b3649' => 'Wieliczka Os. Szymanowskiego (nż)',
# 'b1195' => 'Krzyszkowice Różana (nż)', # nowa nazwa # 'b3652' => 'Wieliczka Różana (nż)',
  'b1248' => 'Krzysztoforzyce Góra (nż)',
  'b3230' => 'Krzysztoforzyce Pętla',
  'b3043' => 'Krzysztoforzyce Sklep (nż)',
  'b1256' => 'Krzysztoforzyce przy Dworze (nż)',
  'b1169' => 'Krzęcin Cmentarz (nż)',
# 'b1357' => 'Krzęcin Częsna (nż)', # nowa nazwa # 'b3332' => 'Krzęcin Szczęsna (nż)',
  'b1098' => 'Krzęcin Kapliczka (nż)',
  'b1096' => 'Krzęcin Kościół',
  'b2928' => 'Krzęcin Pętla',
  'b1095' => 'Krzęcin Sklep',
  'b3332' => 'Krzęcin Szczęsna (nż)',
  'b1099' => 'Krzęcin Szkoła',
# 'b150'  => 'Królowej Jadwigi', # nowa nazwa # 'b3339' => 'Grabowa',
  'b3687' => 'Ks. Luzara (nż)',
  'b3725' => 'Ks. Meiera',
  'b3674' => 'Ks. Łaczka (nż)',
  'b2739' => 'Ks.Targosza (nż)',
# 'b675'  => 'Ks.Łaczka (nż)', # nowa nazwa # 'b3674' => 'Ks. Łaczka (nż)',
# 'b1140' => 'Książniczki Boisko (nż)', # nowa nazwa # 'b3377' => 'Książniczki Paszczykówka (nż)',
  'b1142' => 'Książniczki Centrum',
  'b1143' => 'Książniczki Las (nż)',
  'b3377' => 'Książniczki Paszczykówka (nż)',
  'b544'  => 'Kujawy',
  'b567'  => 'Kuklińskiego',
  'b884'  => 'Kulerzów (nż)',
  'b885'  => 'Kulerzów Wąwóz (nż)',
  'b387'  => 'Kupały',
  'b3176' => 'Kurdwanów P+R',
  'b709'  => 'Kurdwanów Szkoła',
  'b3136' => 'Kurzei',
# 'b98'   => 'Kuźnicy Kołłątajowskiej', # nowa nazwa # 'b3725' => 'Ks. Meiera',
  'b3726' => 'Kuźnicy Kołłątajowskiej',
  'b527'  => 'Kąkolowa (nż)',
  'b759'  => 'Kąpielowa (nż)',
  'b3180' => 'Kępa (nż)',
  'b3637' => 'Kępa Grabska',
# 'b1220' => 'Kłokoczyn (nż)', # nowa nazwa # 'b3306' => 'Kłokoczyn Szkoła (nż)',
  'b3309' => 'Kłokoczyn Machaczki (nż)',
  'b3306' => 'Kłokoczyn Szkoła (nż)',
  'b3074' => 'Kłuszyńska',
  'b140'  => 'Lajkonika (nż)',
  'b694'  => 'Landaua',
  'b750'  => 'Las Borkowski',
  'b2557' => 'Lasek Mogilski',
  'b2790' => 'Lasek Łęgowski (nż)',
# 'b337'  => 'Laskowiec (nż)', # nowa nazwa # 'b3346' => 'Michałowice Laskowiec (nż)',
  'b3217' => 'Lednica Górna (nż)',
# 'b3216' => 'Lednica Górna Chorągwica (nż)', # nowa nazwa # 'b3800' => 'Lednica Górna Świdówka (nż)',
  'b3800' => 'Lednica Górna Świdówka (nż)',
  'b65'   => 'Lekarska',
  'b554'  => 'Lesisko',
# 'b3363' => 'Leszczynowa (nż)', # nowa nazwa # 'b3466' => 'Piastowska',
  'b2619' => 'Leszka Białego',
  'b157'  => 'Leśmiana',
  'b3071' => 'Libertowska (nż)',
# 'b2706' => 'Libertów', # nowa nazwa # 'b3670' => 'Libertów Góra Libertowska',
  'b2638' => 'Libertów Dolny (nż)',
  'b2925' => 'Libertów Droga do Sidziny (nż)',
  'b2711' => 'Libertów Działy (nż)',
  'b3670' => 'Libertów Góra Libertowska',
  'b2710' => 'Libertów Krzyżówka',
  'b2707' => 'Libertów Szkoła',
  'b2772' => 'Libertów Zgodna (nż)',
  'b3373' => 'Libertów Świetlista',
  'b2524' => 'Lindego (nż)',
  'b2686' => 'Lipińskiego',
  'b837'  => 'Lipowskiego (nż)',
  'b561'  => 'Lipska',
  'b289'  => 'Liszki I (nż)',
  'b286'  => 'Liszki Krzyżówka',
  'b2899' => 'Liszki Tyniecka (nż)',
  'b287'  => 'Liszki UG',
  'b2887' => 'Liszki Wołowska Droga (nż)',
  'b126'  => 'Lubicz',
  'b94'   => 'Lublańska',
  'b468'  => 'Lubocza Bugaj (nż)',
  'b467'  => 'Lubocza PKP (nż)',
  'b469'  => 'Lubocza Przychodnia',
  'b470'  => 'Lubocza Szkoła',
  'b471'  => 'Lubocza Trafo (nż)',
  'b472'  => 'Luborzyca',
  'b3778' => 'Luborzyca Piotrowiec (nż)',
  'b3779' => 'Luborzyca Przy Źródle (nż)',
  'b3002' => 'Luborzyca Szkoła',
  'b937'  => 'Lubostroń (nż)',
  'b2808' => 'Ludwinów',
# 'b2905' => 'Lusina (nż)', # nowa nazwa # 'b3326' => 'Lusina Krakowska (nż)',
  'b2936' => 'Lusina Dobrzyczany (nż)',
  'b722'  => 'Lusina Dolna (nż)',
  'b1003' => 'Lusina Dwór',
# 'b2637' => 'Lusina Granica', # nowa nazwa # 'b3373' => 'Libertów Świetlista',
  'b801'  => 'Lusina Górka (nż)',
  'b3326' => 'Lusina Krakowska (nż)',
  'b3301' => 'Lusina Krakówka (nż)',
# 'b3184' => 'Lusina Krakówkaa (nż)', # błąd # 'b3301' => 'Lusina Krakówka (nż)',
  'b2937' => 'Lusina Kraśnik (nż)',
  'b1000' => 'Lusina Pętla',
  'b1002' => 'Lusina Spacerowa',
  'b1001' => 'Lusina Szkoła',
  'b2938' => 'Lusina Zagrody (nż)',
  'b2935' => 'Lusina Zielona',
  'b1196' => 'Lusina Łany (nż)',
# 'b930'  => 'M1 Al. Pokoju', # nowa nazwa # 'b3472' => 'M1 al. Pokoju',
  'b2736' => 'M1 Nowohucka',
# 'b3472' => 'M1 al. Pokoju', # nowa nazwa # 'b3810' => 'Ogród Doświadczeń',
  'b1269' => 'Maciejowice Góra (nż)',
  'b3159' => 'Maciejowice Pętla',
  'b3168' => 'Maciejowice Skrzyżowanie (nż)',
  'b37'   => 'Mackiewicza',
  'b3577' => 'Madejówka (nż)',
  'b3123' => 'Magazynowa (nż)',
  'b96'   => 'Majora',
  'b626'  => 'Makowa',
  'b56'   => 'Makowskiego',
  'b2542' => 'Makuszyńskiego (nż)',
  'b625'  => 'Malborska',
  'b880'  => 'Malborska Szkoła',
  'b310'  => 'Malczewskiego (nż)',
  'b2589' => 'Malinowskiego (nż)',
  'b1130' => 'Marchołta',
  'b3004' => 'Marszowice (nż)',
  'b3003' => 'Marszowice Centrum (nż)',
  'b1319' => 'Marszowice Góry (nż)',
# 'b2983' => 'Maszyce (nż)', # nowa nazwa # 'b3458' => 'Maszyce Sadzawka (nż)',
  'b1174' => 'Maszyce Remiza (nż)',
  'b3458' => 'Maszyce Sadzawka (nż)',
  'b1152' => 'Maszyce Skrzyżowanie (nż)',
# 'b2982' => 'Masłomiąca (nż)', # nowa nazwa # 'b3378' => 'Masłomiąca Długa (nż)',
  'b3378' => 'Masłomiąca Długa (nż)',
  'b3374' => 'Masłomiąca Koźlica (nż)',
  'b2981' => 'Masłomiąca Staw (nż)',
  'b90'   => 'Mazowiecka',
# 'b941'  => 'Mała Góra (nż)', # nowa nazwa # 'b3581' => 'Korepty (nż)', # 'b3577' => 'Madejówka (nż)',
# 'b2496' => 'Mała Wieś (nż)', # nowa nazwa # 'b3798' => 'Mała Wieś Skrzyżowanie (nż)',
  'b3798' => 'Mała Wieś Skrzyżowanie (nż)',
# 'b1263' => 'Mały Płaszów', # nowa nazwa # 'b3310' => 'Mały Płaszów P+R',
  'b3310' => 'Mały Płaszów P+R',
  'b406'  => 'Medweckiego',
  'b3109' => 'Mehoffera',
  'b995'  => 'Meissnera',
  'b454'  => 'Meksyk (nż)',
  'b3130' => 'Merkuriusza Polskiego',
  'b85'   => 'Miasteczko Studenckie AGH',
# 'b331'  => 'Michałowice (nż)', # nowa nazwa # 'b3594' => 'Michałowice Dąbrowskich (nż)',
  'b1058' => 'Michałowice Banasiówka (nż)',
  'b2967' => 'Michałowice Brzozowa (nż)',
  'b3595' => 'Michałowice Centrum',
  'b3594' => 'Michałowice Dąbrowskich (nż)',
  'b2963' => 'Michałowice Gościniec (nż)',
# 'b2964' => 'Michałowice Górna (nż)', # nowa nazwa # 'b3597' => 'Michałowice Na Stoku (nż)',
  'b3596' => 'Michałowice Górna (nż)',
# 'b333'  => 'Michałowice I', # nowa nazwa # 'b3595' => 'Michałowice Centrum',
# 'b336'  => 'Michałowice II (nż)', # nowa nazwa # 'b3596' => 'Michałowice Górna (nż)',
  'b3355' => 'Michałowice Jana Pawła II (nż)',
  'b332'  => 'Michałowice Komora (nż)',
# 'b905'  => 'Michałowice Koźlica (nż)', # nowa nazwa # 'b3374' => 'Masłomiąca Koźlica (nż)',
  'b2506' => 'Michałowice Kwiaty Polne (nż)',
  'b3356' => 'Michałowice Las Michałowski',
# 'b2507' => 'Michałowice Las Michałowski (nż)', # nowa nazwa # 'b3355' => 'Michałowice Jana Pawła II (nż)',
  'b3346' => 'Michałowice Laskowiec (nż)',
  'b335'  => 'Michałowice Lecznica (nż)',
  'b2965' => 'Michałowice Michałówka (nż)',
  'b3597' => 'Michałowice Na Stoku (nż)',
  'b1145' => 'Michałowice Ogrodowa (nż)',
  'b2729' => 'Michałowice Ośrodek Zdrowia',
  'b3582' => 'Michałowice P+R',
  'b1055' => 'Michałowice Ujęcie Wody (nż)',
  'b3347' => 'Michałowice Warszawka (nż)',
  'b104'  => 'Miechowity',
  'b3384' => 'Miejskie Centrum Opieki',
  'b3011' => 'Millana (nż)',
  'b362'  => 'Miodowa',
  'b375'  => 'Mistrzejowice',
  'b2538' => 'Miśnieńska',
# 'b2882' => 'Mników Droga do Kaszowa (nż)', # nowa nazwa # 'b3297' => 'Mników Sklep (nż)',
  'b3232' => 'Mników Granica (nż)',
  'b2714' => 'Mników Pańska Góra (nż)',
  'b3296' => 'Mników Remiza (nż)',
  'b2715' => 'Mników Skały',
# 'b248'  => 'Mników Sklep (nż)', # nowa nazwa # 'b3296' => 'Mników Remiza (nż)',
  'b3297' => 'Mników Sklep (nż)',
  'b3104' => 'Mników Zarynnie (nż)',
  'b2516' => 'Mobilis',
  'b2694' => 'Mochnaniec (nż)',
# 'b986'  => 'Modlnica', # nowa nazwa # 'b3554' => 'Modlnica Szkoła',
  'b3493' => 'Modlnica Cicha (nż)',
# 'b968'  => 'Modlnica I Kolonia (nż)', # nowa nazwa # 'b3544' => 'Modlnica Kolonia (nż)',
# 'b969'  => 'Modlnica II (nż)', # nowa nazwa # 'b3545' => 'Modlnica Komora (nż)',
  'b3544' => 'Modlnica Kolonia (nż)',
  'b3545' => 'Modlnica Komora (nż)',
  'b3555' => 'Modlnica Kościelna (nż)',
  'b3543' => 'Modlnica Podchruście (nż)',
  'b985'  => 'Modlnica Skrzyżowanie (nż)',
  'b3554' => 'Modlnica Szkoła',
# 'b2875' => 'Modlnica Trojadyn Szydło (nż)', # nowa nazwa #
# 'b984'  => 'Modlniczka', # nowa nazwa # 'b3553' => 'Modlniczka Dworska',
  'b3553' => 'Modlniczka Dworska',
# 'b983'  => 'Modlniczka I (nż)', # nowa nazwa # 'b3552' => 'Modlniczka Willowa (nż)',
  'b3251' => 'Modlniczka Leroy Merlin (nż)',
  'b197'  => 'Modlniczka Mała',
  'b1353' => 'Modlniczka Poligon (nż)',
  'b1046' => 'Modlniczka Trzcie (nż)',
  'b3552' => 'Modlniczka Willowa (nż)',
  'b2499' => 'Mogilany Cicha (nż)',
  'b888'  => 'Mogilany Cmentarz (nż)',
  'b2953' => 'Mogilany Kopce (nż)',
  'b3313' => 'Mogilany Krótka (nż)',
  'b793'  => 'Mogilany Ośrodek Zdrowia (nż)',
  'b792'  => 'Mogilany Rynek',
  'b794'  => 'Mogilany Wiadukt (nż)',
# 'b806'  => 'Mogilany Włosań (nż)', # nowa nazwa # 'b3313' => 'Mogilany Krótka (nż)',
# 'b233'  => 'Morawica', # nowa nazwa # 'b3386' => 'Morawica Centrum',
  'b3386' => 'Morawica Centrum',
# 'b234'  => 'Morawica Cmentarz (nż)', # nowa nazwa # 'b3387' => 'Morawica Szkoła (nż)',
  'b232'  => 'Morawica Krzyżówka',
  'b231'  => 'Morawica Mostek (nż)',
  'b3105' => 'Morawica Rudki (nż)',
  'b3387' => 'Morawica Szkoła (nż)',
  'b3119' => 'Morcinka (nż)',
  'b1239' => 'Most Kotlarski (nż)',
  'b565'  => 'Motyla',
  'b460'  => 'Mrozowa (nż)',
# 'b974'  => 'Murownia (nż)', # nowa nazwa # 'b3550' => 'Biały Kościół Murownia (nż)',
# 'b3060' => 'Murownia Pętla', # nowa nazwa # 'b3559' => 'Biały Kościół Murownia Pętla',
  'b1015' => 'Muzeum Armii Krajowej (nż)',
  'b3141' => 'Muzeum Narodowe',
# 'b8'    => 'Mydlniki', # nowa nazwa # 'b3564' => 'Wierzyńskiego',
  'b2525' => 'Mydlniki Granica Miasta (nż)',
# 'b9'    => 'Mydlniki Stawy (nż)', # nowa nazwa # 'b3565' => 'Cmentarz Mydlniki (nż)',
  'b3560' => 'Mydlniki Wapiennik P+R',
  'b740'  => 'Myślenicka (nż)',
# 'b3262' => 'Młodej Polski (nż)', # tymczasowy - przebudowa linii do Bronowic
  'b1144' => 'Młodziejowice Młyn (nż)',
  'b1141' => 'Młodziejowice Park',
  'b636'  => 'Młodzieży (nż)',
# 'b1040' => 'Młynka (nż)', # nowa nazwa # 'b3522' => 'Młynka Dolna (nż)',
  'b3522' => 'Młynka Dolna (nż)',
# 'b218'  => 'Młynka I (nż)', # nowa nazwa # 'b3520' => 'Młynka Kalwaryjska (nż)',
  'b3520' => 'Młynka Kalwaryjska (nż)',
  'b1'    => 'Młynka Pętla',
  'b2908' => 'Młynówka SKA (nż)',
# 'b3760' => 'Na Barciach', # tymczasowy - przebudowa Al. 29 Listopada
  'b2616' => 'Na Budzyniu',
  'b273'  => 'Na Krępaku (nż)',
  'b550'  => 'Na Załęczu',
# 'b549'  => 'Na Załęczu Szkoła (nż)', # nowa nazwa # 'b3337' => 'Archiwum UMK (nż)',
  'b645'  => 'Nad Drwiną',
  'b2541' => 'Nad Dłubnią',
  'b2656' => 'Nadbrzezie (nż)',
  'b3348' => 'Narama Graniczna Sklep (nż)',
  'b3349' => 'Narama Księża (nż)',
  'b2966' => 'Narama Remiza',
  'b121'  => 'Narzymskiego',
  'b2606' => 'Natansona',
  'b3524' => 'Nawojowa Góra Gwoździec (nż)',
# 'b1042' => 'Nawojowa Góra I (nż)', # nowa nazwa # 'b3523' => 'Nawojowa Góra Zagrody (nż)',
# 'b1043' => 'Nawojowa Góra II (nż)', # nowa nazwa # 'b3524' => 'Nawojowa Góra Gwoździec (nż)',
  'b3489' => 'Nawojowa Góra Pisarska (nż)',
  'b3523' => 'Nawojowa Góra Zagrody (nż)',
  'b2775' => 'Nałkowskiej',
  'b2594' => 'Niebieska Autostrada (nż)',
  'b3278' => 'Niebyła (nż)',
  'b1327' => 'Niedźwiedź Felix (nż)',
  'b1326' => 'Niedźwiedź PKP (nż)',
# 'b1187' => 'Nielepice', # nowa nazwa # 'b3424' => 'Nielepice Pętla',
  'b3424' => 'Nielepice Pętla',
  'b1235' => 'Nielepice Stadnina (nż)',
  'b1278' => 'Niepołomice Batorego (nż)',
  'b1279' => 'Niepołomice Batorego II (nż)',
  'b1306' => 'Niepołomice Boryczów (nż)',
  'b1300' => 'Niepołomice Diesla (nż)',
  'b1276' => 'Niepołomice Dworzec',
  'b1289' => 'Niepołomice Jazy (nż)',
  'b1290' => 'Niepołomice Jazy II (nż)',
  'b964'  => 'Niepołomice Kolejowa (nż)',
  'b1303' => 'Niepołomice Kościuszki (nż)',
  'b1298' => 'Niepołomice Kątek (nż)',
# 'b1275' => 'Niepołomice Moczydło (nż)', # nowa nazwa # 'b1276' => 'Niepołomice Dworzec',
  'b1297' => 'Niepołomice Pasternik (nż)',
  'b1296' => 'Niepołomice Podgrabie (nż)',
  'b1299' => 'Niepołomice Poręby (nż)',
  'b1302' => 'Niepołomice Płaszowska I (nż)',
  'b1277' => 'Niepołomice Rynek',
  'b1307' => 'Niepołomice Wielicka (nż)',
  'b1301' => 'Niepołomice Wodna (nż)',
  'b2688' => 'Norymberska',
# 'b280'  => 'Nowa Wieś (nż)', # nowa nazwa # 'b3392' => 'Nowa Wieś Szlachecka Sklep (nż)',
# 'b1197' => 'Nowa Wieś Jesionka (nż)', # nowa nazwa # 'b3398' => 'Nowa Wieś Szlachecka Jesionka (nż)',
# 'b281'  => 'Nowa Wieś Kapliczka (nż)', # nowa nazwa # 'b3393' => 'Nowa Wieś Szlachecka Kapliczka (nż)',
# 'b279'  => 'Nowa Wieś Kościół (nż)', # nowa nazwa # 'b3391' => 'Nowa Wieś Szlachecka Kościół (nż)',
# 'b278'  => 'Nowa Wieś Szlachecka', # nowa nazwa # 'b3390' => 'Nowa Wieś Szlachecka Pętla',
  'b3398' => 'Nowa Wieś Szlachecka Jesionka (nż)',
  'b3393' => 'Nowa Wieś Szlachecka Kapliczka (nż)',
  'b3391' => 'Nowa Wieś Szlachecka Kościół (nż)',
  'b3390' => 'Nowa Wieś Szlachecka Pętla',
  'b3392' => 'Nowa Wieś Szlachecka Sklep (nż)',
  'b395'  => 'Nowolipki (nż)',
  'b715'  => 'Nowosądecka',
  'b3175' => 'Nowy Bieżanów P+R',
  'b2581' => 'Nowy Bieżanów Południe',
  'b71'   => 'Nowy Kleparz',
  'b2582' => 'Nowy Prokocim',
  'b3068' => 'Obserwatorium (nż)',
  'b1313' => 'Ochmanów Oknoplast (nż)',
# 'b2727' => 'Ochmanów Otaczarnia (nż)', # nowa nazwa # 'b1313' => 'Ochmanów Oknoplast (nż)',
# 'b1171' => 'Ochodza', # nowa nazwa # 'b3331' => 'Ochodza Dwór',
  'b1329' => 'Ochodza Dom Ludowy (nż)',
  'b3331' => 'Ochodza Dwór',
  'b1331' => 'Ochodza Odwiśle',
  'b1330' => 'Ochodza Staw (nż)',
  'b2951' => 'Ochojno Dąbrówki',
  'b863'  => 'Ochojno Kamieniec',
  'b861'  => 'Ochojno Remiza',
  'b860'  => 'Ochojno Skrzyżowanie',
  'b2655' => 'Oczyszczalnia Ścieków \'Kujawy\' (nż)',
  'b553'  => 'Odmętowa',
  'b369'  => 'Ofiar Dąbia',
  'b3810' => 'Ogród Doświadczeń',
  'b18'   => 'Ojcowska',
  'b16'   => 'Ojcowska Dworek',
  'b17'   => 'Ojcowska Wągroda',
  'b3527' => 'Ojców Zamek',
  'b3528' => 'Ojców Złota Góra',
  'b103'  => 'Olsza II',
  'b161'  => 'Olszanica Bory',
  'b158'  => 'Olszanica Kapliczka (nż)',
  'b2534' => 'Olszanica Ogródki Działkowe (nż)',
  'b102'  => 'Olszecka',
  'b761'  => 'Opatkowice',
  'b760'  => 'Opatkowice Wiadukt (nż)',
  'b2634' => 'Opatkowice Zadworze',
  'b92'   => 'Opolska Estakada',
  'b48'   => 'Opolska Kładka',
  'b431'  => 'Orkana',
  'b3064' => 'Orszy-Broniewskiego',
# 'b361'  => 'Orzeszkowej', # tymczasowy - przebudowa ul. Krakowskiej
  'b3187' => 'Orłowskiego (nż)',
  'b3114' => 'Os. Akademickie PK',
  'b111'  => 'Os. Dywizjonu 303',
  'b3727' => 'Os. Gotyk',
  'b421'  => 'Os. Górali',
  'b402'  => 'Os. Jagiellońskie',
  'b386'  => 'Os. Kalinowe',
  'b756'  => 'Os. Kliny',
  'b413'  => 'Os. Kolorowe',
  'b3445' => 'Os. Kościuszkowskie',
  'b710'  => 'Os. Kurdwanów',
  'b28'   => 'Os. Marszowiec',
  'b2737' => 'Os. Mistrzejowice Nowe',
  'b391'  => 'Os. Na Lotnisku',
  'b424'  => 'Os. Na Skarpie',
  'b939'  => 'Os. Na Stoku',
  'b436'  => 'Os. Na Stoku Szkoła',
  'b108'  => 'Os. Oświecenia',
  'b378'  => 'Os. Piastów',
  'b2812' => 'Os. Podwawelskie',
  'b582'  => 'Os. Robotnicze',
  'b390'  => 'Os. Strusia',
  'b428'  => 'Os. Wandy',
  'b430'  => 'Os. Willowe',
  'b418'  => 'Os. Zgody',
  'b422'  => 'Os. Zielone',
  'b377'  => 'Os. Złotego Wieku',
# 'b404'  => 'Os.Kościuszkowskie', # nowa nazwa # 'b3445' => 'Os. Kościuszkowskie',
# 'b1243' => 'Os.Łokietka', # nowa nazwa # 'b3460' => 'Starego Wiarusa',
  'b2643' => 'Ostafina',
  'b3465' => 'Owcy-Orwicza',
# 'b2969' => 'Owczary (nż)', # nowa nazwa # 'b3455' => 'Owczary Długa (nż)',
# 'b2631' => 'Owczary Długa (nż)', # nowa nazwa # 'b3357' => 'Owczary Spacerowa (nż)',
  'b3455' => 'Owczary Długa (nż)',
  'b2632' => 'Owczary Gajowa (nż)',
  'b2630' => 'Owczary Górna (nż)',
  'b2968' => 'Owczary Pętla',
  'b3357' => 'Owczary Spacerowa (nż)',
  'b817'  => 'PB',
  'b3135' => 'PCK',
  'b819'  => 'PP',
  'b818'  => 'PW',
# 'b2526' => 'Pachońskiego', # nowa nazwa # 'b3723' => 'Pachońskiego P+R',
  'b3723' => 'Pachońskiego P+R',
  'b963'  => 'Panieńskich Skał',
  'b3731' => 'Papierni Prądnickich',
  'b2560' => 'Park \'Skały Twardowskiego\' (nż)',
  'b143'  => 'Park Decjusza',
  'b1004' => 'Park Wodny',
  'b3149' => 'Park Zdrojowy',
  'b15'   => 'Pasternik (nż)',
  'b2776' => 'Petrażyckiego (nż)',
  'b3070' => 'Petrażyckiego Osiedle (nż)',
  'b3191' => 'Petőfiego (nż)',
  'b716'  => 'Piaski Nowe',
  'b687'  => 'Piaski Wielkie',
  'b3177' => 'Piaskowa (nż)',
  'b379'  => 'Piasta Kołodzieja',
  'b3466' => 'Piastowska',
  'b2529' => 'Piaszczysta',
# 'b270'  => 'Piekary', # nowa nazwa # 'b3389' => 'Piekary Centrum',
  'b2898' => 'Piekary Borki (nż)',
  'b3389' => 'Piekary Centrum',
  'b2900' => 'Piekary Dół (nż)',
  'b868'  => 'Piekary Górne',
  'b2897' => 'Piekary Korea (nż)',
  'b2896' => 'Piekary Na Brzegu (nż)',
  'b1189' => 'Piekary Pałac (nż)',
  'b269'  => 'Piekary Sklep (nż)',
# 'b2985' => 'Pielgrzymowice (nż)', # nowa nazwa # 'b3379' => 'Pielgrzymowice Wierzbowa (nż)',
  'b2986' => 'Pielgrzymowice Granica (nż)',
  'b2984' => 'Pielgrzymowice Pętla',
  'b3379' => 'Pielgrzymowice Wierzbowa (nż)',
  'b3035' => 'Pielęgniarek',
  'b119'  => 'Pilotów',
  'b3672' => 'Piltza',
# 'b1036' => 'Pisary (nż)', # nowa nazwa # 'b3420' => 'Pisary Spacerowa (nż)',
  'b3421' => 'Pisary Akacjowa (nż)',
  'b1236' => 'Pisary Dwór (nż)',
  'b3531' => 'Pisary Dąbrówki (nż)',
  'b2860' => 'Pisary Kasztanowa (nż)',
# 'b1037' => 'Pisary Kiosk (nż)', # nowa nazwa # 'b3421' => 'Pisary Akacjowa (nż)',
# 'b1038' => 'Pisary Mleczarnia (nż)', # nowa nazwa # 'b3422' => 'Pisary Mleczna (nż)',
  'b3422' => 'Pisary Mleczna (nż)',
# 'b1041' => 'Pisary Skrzyżowanie (nż)', # nowa nazwa # 'b3489' => 'Nawojowa Góra Pisarska (nż)',
  'b3420' => 'Pisary Spacerowa (nż)',
# 'b3263' => 'Plac Axentowicza', # tymczasowy - przebudowa linii do Bronowic
  'b570'  => 'Plac Bohaterów Getta',
  'b2744' => 'Plac Centralny im. R.Reagana',
  'b79'   => 'Plac Inwalidów',
  'b3733' => 'Plac Na Stawach',
  'b360'  => 'Plac Wolnica',
  'b1360' => 'Plac Wszystkich Świętych',
  'b3681' => 'Plastusia (nż)',
  'b47'   => 'Pleszowska',
  'b458'  => 'Pleszów',
  'b357'  => 'Poczta Główna',
  'b944'  => 'Pod Fortem',
  'b1014' => 'Pod Lipą (nż)',
  'b812'  => 'Podgaje',
  'b603'  => 'Podgórki Tynieckie',
  'b3158' => 'Podgórze SKA',
  'b517'  => 'Podstawie (nż)',
  'b3529' => 'Podstolice Centrum',
  'b3530' => 'Podstolice Zamłynie (nż)',
  'b644'  => 'Podwierzbie',
  'b1311' => 'Podłęże Balachówka (nż)',
  'b1309' => 'Podłęże Centrum (nż)',
  'b2728' => 'Podłęże Przedszkole (nż)',
  'b3796' => 'Podłęże Remiza (nż)',
# 'b1310' => 'Podłęże Straż (nż)', # nowa nazwa # 'b3796' => 'Podłęże Remiza (nż)',
  'b956'  => 'Polana Żywiecka (nż)',
  'b3482' => 'Polanka Hallera Centrum',
  'b1093' => 'Polanka Hallera Dwór',
# 'b1318' => 'Polanowice (nż)', # nowa nazwa # 'b3288' => 'Polanowice Boisko (nż)',
  'b3288' => 'Polanowice Boisko (nż)',
  'b1323' => 'Polanowice Kolonia (nż)',
  'b73'   => 'Politechnika',
  'b380'  => 'Popielidów',
  'b833'  => 'Poronińska (nż)',
  'b97'   => 'Powstańców',
  'b1155' => 'Powstańców Garaże',
  'b3195' => 'Powstańców Magazyny (nż)',
  'b3655' => 'Powstańców Wiadukt',
  'b2806' => 'Poziomkowa',
  'b3648' => 'Połomskiego (nż)',
  'b580'  => 'Praska (nż)',
  'b3010' => 'Prawocheńskiego (nż)',
  'b2746' => 'Prokocim Rynek',
  'b682'  => 'Prokocim Szpital',
  'b684'  => 'Prokocim UJ',
  'b3734' => 'Promienistych',
  'b633'  => 'Prosta',
# 'b479'  => 'Prussy', # błąd # 'b3300' => 'Prusy',
# 'b3300' => 'Prusy', # nowa nazwa # 'b3777' => 'Prusy Rondo',
  'b3776' => 'Prusy Kościół (nż)',
  'b3777' => 'Prusy Rondo',
  'b478'  => 'Prusy Szkoła (nż)',
# 'b477'  => 'Prusy WSR (nż)', # nowa nazwa # 'b3776' => 'Prusy Kościół (nż)',
  'b671'  => 'Pruszyńskiego',
# 'b3219' => 'Przebieczany', # nowa nazwa # 'b3802' => 'Przebieczany Gdowska',
  'b3802' => 'Przebieczany Gdowska',
  'b3769' => 'Przeginia Dom Ludowy (nż)',
  'b1214' => 'Przeginia Duchowna (nż)',
# 'b1228' => 'Przeginia Duchowna Bar (nż)', # nowa nazwa # 'b3407' => 'Przeginia Duchowna Kościół (nż)',
# 'b1199' => 'Przeginia Duchowna Centrum', # nowa nazwa # 'b3399' => 'Przeginia Duchowna Remiza',
  'b3407' => 'Przeginia Duchowna Kościół (nż)',
  'b3399' => 'Przeginia Duchowna Remiza',
  'b1198' => 'Przeginia Duchowna Szkoła (nż)',
  'b3761' => 'Przeginia Kościół',
# 'b1227' => 'Przeginia Narodowa (nż)', # nowa nazwa # 'b3406' => 'Przeginia Narodowa Bunar (nż)',
# 'b2906' => 'Przeginia Narodowa Bonar (nż)', # nowa nazwa # 'b3400' => 'Przeginia Narodowa Dwór (nż)',
  'b3406' => 'Przeginia Narodowa Bunar (nż)',
  'b3400' => 'Przeginia Narodowa Dwór (nż)',
  'b3767' => 'Przeginia Ostra Góra (nż)',
  'b3768' => 'Przeginia Skotnica (nż)',
  'b316'  => 'Przegon',
  'b275'  => 'Przegorzały',
  'b3182' => 'Przegorzały Obwodnica (nż)',
  'b641'  => 'Przewóz',
  'b904'  => 'Przy Kuźni (nż)',
  'b2530' => 'Przybyszewskiego',
  'b3790' => 'Przybysławice Centrum',
# 'b190'  => 'Przybysławice I (nż)', # nowa nazwa # 'b3789' => 'Przybysławice Na Stoczki (nż)',
# 'b191'  => 'Przybysławice II', # nowa nazwa # 'b3790' => 'Przybysławice Centrum',
# 'b1084' => 'Przybysławice III (nż)', # nowa nazwa # 'b3791' => 'Przybysławice Na Lipowiec (nż)',
  'b3791' => 'Przybysławice Na Lipowiec (nż)',
  'b3789' => 'Przybysławice Na Stoczki (nż)',
# 'b745'  => 'Przykopy (nż)', # nowa nazwa # 'b3647' => 'Turowicza',
  'b532'  => 'Przylasek Rusiecki',
  'b3542' => 'Przylasek Rusiecki Kąpielisko',
  'b3688' => 'Przylasek Rusiecki Północ (nż)',
  'b543'  => 'Przylasek Wyciąski (nż)',
  'b2527' => 'Prądnik Biały',
  'b3722' => 'Prądnik Biały Wschód',
# 'b870'  => 'Prądnik Biały Zachód', # nowa nazwa # 'b3787' => 'Vetulaniego',
  'b3793' => 'Prądnik Biały Zachód',
  'b100'  => 'Prądnik Czerwony',
  'b3620' => 'Pszenna',
  'b1164' => 'Pszona',
  'b1253' => 'Puszkarska',
  'b2569' => 'Pychowice',
  'b730'  => 'Pytlasińskiego',
  'b3124' => 'Półłanki',
  'b72'   => 'Pędzichów',
# 'b2703' => 'Pękowice', # nowa nazwa # 'b3474' => 'Pękowice Fort',
  'b3474' => 'Pękowice Fort',
  'b3440' => 'Pękowice Ojcowska',
  'b3575' => 'Pękowicka',
  'b2873' => 'Płaszowska',
  'b564'  => 'Płaszów Szkoła',
  'b660'  => 'Płk. Dąbka',
# 'b354'  => 'Raciborowice', # nowa nazwa # 'b3452' => 'Raciborowice Wawelska',
  'b1138' => 'Raciborowice Centrum',
  'b2988' => 'Raciborowice Granica (nż)',
  'b3452' => 'Raciborowice Wawelska',
  'b154'  => 'Raczkiewicza (nż)',
  'b3638' => 'Radio Kraków',
# 'b1033' => 'Radwanowice I (nż)', # nowa nazwa # 'b3490' => 'Rudawa 21 Lipca (nż)',
  'b3208' => 'Radwanowice Krzeszowicka (nż)',
  'b1032' => 'Radwanowice Pętla',
  'b132'  => 'Radzikowskiego',
  'b1376' => 'Radzikowskiego Osiedle',
  'b788'  => 'Radziszów Centrum',
  'b2774' => 'Radziszów Cmentarz (nż)',
  'b789'  => 'Radziszów Kamionna (nż)',
  'b1182' => 'Radziszów Kładka (nż)',
  'b797'  => 'Radziszów Leśniczówka (nż)',
  'b1186' => 'Radziszów PKP',
  'b798'  => 'Radziszów Podlesie (nż)',
  'b3233' => 'Radziszów Podlesie Las (nż)',
  'b1184' => 'Radziszów Podwale (nż)',
  'b2477' => 'Radziszów Stare Sanatorium (nż)',
  'b3075' => 'Radziszów Szpital',
  'b786'  => 'Radziszów Włosanka (nż)',
  'b2491' => 'Radziszów Za Mogiłką (nż)',
  'b1183' => 'Radziszów Zacisze (nż)',
  'b787'  => 'Radziszów Zadworze (nż)',
  'b1185' => 'Radziszów Zawodzie (nż)',
  'b695'  => 'Rajsko',
  'b1325' => 'Ratajów Skrzyżowanie (nż)',
  'b3585' => 'Rawałowice Góra (nż)',
  'b3583' => 'Rawałowice Kapliczka',
  'b3584' => 'Rawałowice Skrzyżowanie (nż)',
  'b3192' => 'Reduta (nż)',
  'b502'  => 'Resztówka',
  'b2568' => 'Rodzinna',
  'b3041' => 'Rondo 308. Dywizjonu',
  'b1066' => 'Rondo Barei',
  'b408'  => 'Rondo Czyżyńskie',
  'b3338' => 'Rondo Grunwaldzkie',
  'b365'  => 'Rondo Grzegórzeckie',
  'b2539' => 'Rondo Hipokratesa',
  'b2745' => 'Rondo Kocmyrzowskie im. Ks. Gorzelanego',
  'b610'  => 'Rondo Matecznego',
  'b125'  => 'Rondo Mogilskie',
  'b118'  => 'Rondo Młyńskie',
  'b12'   => 'Rondo Ofiar Katynia',
  'b383'  => 'Rondo Piastowskie',
  'b2689' => 'Rostworowskiego',
  'b589'  => 'Ruczaj',
# 'b217'  => 'Rudawa (nż)', # nowa nazwa # 'b2924' => 'Rudawa Stadion (nż)',
  'b3490' => 'Rudawa 21 Lipca (nż)',
# 'b1030' => 'Rudawa Bloki (nż)', # nowa nazwa # 'b3418' => 'Rudawa Osiedle (nż)',
# 'b1031' => 'Rudawa Kościół', # nowa nazwa # 'b3419' => 'Rudawa Rynek',
  'b1064' => 'Rudawa Młyn (nż)',
  'b3418' => 'Rudawa Osiedle (nż)',
  'b1059' => 'Rudawa PKP',
  'b3419' => 'Rudawa Rynek',
  'b2924' => 'Rudawa Stadion (nż)',
  'b1039' => 'Rudawa Szkoła',
# 'b2894' => 'Rusocice Droga do Kościoła (nż)', # nowa nazwa # 'b3308' => 'Rusocice Na Brzegu (nż)',
  'b3405' => 'Rusocice Granica (nż)',
  'b1260' => 'Rusocice Jałowce (nż)',
  'b3308' => 'Rusocice Na Brzegu (nż)',
  'b1229' => 'Rusocice Skład (nż)',
# 'b2893' => 'Rusocice Stacja Benzynowa (nż)', # nowa nazwa # 'b3307' => 'Rusocice Stacja Paliw (nż)',
# 'b3307' => 'Rusocice Stacja Paliw (nż)', # nowa nazwa # 'b3405' => 'Rusocice Granica (nż)',
  'b1230' => 'Rusocice Wieś',
  'b1261' => 'Rusocice Załęg (nż)',
  'b1225' => 'Rusocice Łęg (nż)',
  'b520'  => 'Ruszcza',
  'b653'  => 'Rybitwy Dom Kultury',
  'b652'  => 'Rybitwy Rozjazd (nż)',
  'b654'  => 'Rybitwy Sklep (nż)',
# 'b1209' => 'Rybna', # nowa nazwa # 'b3299' => 'Rybna Kościół',
  'b1367' => 'Rybna Dolna',
  'b3103' => 'Rybna Droga do Sanki (nż)', # powinno być # 'b3103' => 'Sanka Skrzyżowanie',
  'b1213' => 'Rybna Dół (nż)',
# 'b1368' => 'Rybna Granica (nż)', # nowa nazwa # 'b3463' => 'Rybna Ośrodek Zdrowia (nż)',
  'b3299' => 'Rybna Kościół',
  'b1208' => 'Rybna Nowy Świat',
  'b2884' => 'Rybna Nowy Świat Góra (nż)',
# 'b1212' => 'Rybna Ośrodek Zdrowia (nż)', # nowa nazwa # 'b3462' => 'Rybna Pawilon (nż)',
  'b3463' => 'Rybna Ośrodek Zdrowia (nż)',
  'b3462' => 'Rybna Pawilon (nż)',
  'b2885' => 'Rybna Szkoła (nż)',
  'b1341' => 'Rybna Zagórze (nż)',
  'b579'  => 'Rynek Dębnicki',
  'b616'  => 'Rynek Fałęcki',
  'b1262' => 'Rzebika',
  'b611'  => 'Rzemieślnicza',
# 'b3009' => 'Rzepakowa (nż)', # nowa nazwa # 'b3688' => 'Przylasek Rusiecki Północ (nż)',
  'b3690' => 'Rzepakowa (nż)',
  'b2654' => 'Rzepakowa Świetlica (nż)',
  'b153'  => 'Rzepichy (nż)',
# 'b855'  => 'Rzeszotary', # nowa nazwa # 'b3321' => 'Rzeszotary Dworska',
  'b3321' => 'Rzeszotary Dworska',
# 'b859'  => 'Rzeszotary Górne (nż)', # nowa nazwa # 'b3322' => 'Rzeszotary Remiza (nż)',
  'b2940' => 'Rzeszotary Panciawa (nż)',
  'b2939' => 'Rzeszotary Panciawa Pętla',
  'b2778' => 'Rzeszotary Pod Dębiną (nż)',
  'b858'  => 'Rzeszotary Polanki (nż)',
  'b3322' => 'Rzeszotary Remiza (nż)',
  'b857'  => 'Rzeszotary Szkoła (nż)',
  'b2732' => 'Rzeszotary Tempo (nż)',
  'b856'  => 'Rzeszotary Trafo (nż)',
  'b842'  => 'Rzeszotary Zalesie (nż)',
  'b1087' => 'Rzozów Baseny (nż)',
  'b1088' => 'Rzozów I (nż)',
  'b1180' => 'Rzozów PKP (nż)',
  'b1179' => 'Rzozów Skotnica (nż)',
  'b1089' => 'Rzozów Szkoła',
  'b1181' => 'Rzozów Zagonnie (nż)',
  'b196'  => 'Rząska Autostrada (nż)',
  'b2990' => 'Rząska Cmentarz (nż)',
  'b193'  => 'Rząska Jednostka Wojskowa (nż)',
  'b3487' => 'Rząska Podkamycze',
  'b3199' => 'Rząska Szkoła',
  'b194'  => 'Rząska UR (nż)',
  'b55'   => 'Różyckiego',
# 'b3061' => 'Rączna Bażanty (nż)', # nowa nazwa # 'b3408' => 'Rączna Gołębiec (nż)',
  'b3395' => 'Rączna Bażanty (nż)',
# 'b2902' => 'Rączna Boisko (nż)', # nowa nazwa # 'b3671' => 'Rączna Cracovia Centrum Treningowe (nż)',
  'b3671' => 'Rączna Cracovia Centrum Treningowe (nż)',
  'b1217' => 'Rączna Dzikowiec (nż)',
  'b3408' => 'Rączna Gołębiec (nż)',
  'b296'  => 'Rączna Kapliczka (nż)',
  'b1370' => 'Rączna Kościół (nż)',
# 'b2901' => 'Rączna OSP (nż)', # nowa nazwa # 'b3396' => 'Rączna Remiza (nż)',
  'b306'  => 'Rączna Osiedle (nż)',
  'b1216' => 'Rączna Podlas (nż)',
  'b3396' => 'Rączna Remiza (nż)',
  'b3044' => 'Rżąka',
# 'b2762' => 'Sadowie (nż)', # nowa nazwa # 'b3290' => 'Sadowie Wiadukt (nż)',
  'b3290' => 'Sadowie Wiadukt (nż)',
  'b311'  => 'Salwator',
  'b3152' => 'Sapalskiego (nż)',
  'b559'  => 'Saska',
  'b3128' => 'Sawiczewskich',
# 'b3261' => 'Sewera (nż)', # tymczasowy - przebudowa linii do Bronowic
  'b772'  => 'Sidzina',
  'b943'  => 'Sieborowice (nż)',
  'b542'  => 'Siejówka (nż)',
  'b142'  => 'Sielanka',
  'b2547' => 'Sieroszewskiego (nż)',
  'b32'   => 'Siewna',
  'b33'   => 'Siewna Wiadukt',
  'b1166' => 'Sikorki',
  'b2556' => 'Siwka (nż)',
  'b264'  => 'Skalna (nż)',
# 'b2731' => 'Skarżyńskiego', # zlikwidowany
  'b779'  => 'Skawina',
  'b1133' => 'Skawina 29 Listopada',
  'b2473' => 'Skawina Ajka',
  'b2854' => 'Skawina Bukowska (nż)',
  'b2863' => 'Skawina Centrum Sportowe',
  'b2475' => 'Skawina Cmentarz',
  'b1137' => 'Skawina Cmentarz Komunalny',
  'b1104' => 'Skawina Elektrownia (nż)',
  'b2487' => 'Skawina Energetyków (nż)',
  'b3008' => 'Skawina Energetyków Przejazd PKP (nż)',
  'b2853' => 'Skawina Graniczna (nż)',
  'b3598' => 'Skawina Groble (nż)',
  'b1086' => 'Skawina Koncentraty',
  'b2930' => 'Skawina Kopernika (nż)',
  'b1101' => 'Skawina Korabnicka (nż)',
  'b1102' => 'Skawina Korabnicka Szkoła (nż)',
  'b2481' => 'Skawina Korabniki',
  'b2494' => 'Skawina Nad Potokiem (nż)',
  'b3660' => 'Skawina Obwodnica (nż)',
# 'b2868' => 'Skawina Ofiar Katynia', # nowa nazwa # 'b3451' => 'Kopanka Ofiar Katynia',
  'b2929' => 'Skawina Ogrody (nż)',
  'b3502' => 'Skawina Os. Radziszowskie (nż)',
# 'b2471' => 'Skawina Os.Radziszowskie (nż)', # nowa nazwa # 'b3502' => 'Skawina Os. Radziszowskie (nż)',
  'b3336' => 'Skawina Piastowska (nż)',
  'b2867' => 'Skawina Pileckiego',
  'b1103' => 'Skawina Piłsudskiego',
  'b1107' => 'Skawina Podbory (nż)',
  'b3327' => 'Skawina Podgórki',
# 'b2927' => 'Skawina Podgórki Skawińskie', # nowa nazwa # 'b3327' => 'Skawina Podgórki',
  'b2476' => 'Skawina Podlipki',
  'b2474' => 'Skawina Popiełuszki',
  'b2472' => 'Skawina Radziszowska (nż)',
  'b2486' => 'Skawina Robotnicza',
  'b781'  => 'Skawina Rynek',
  'b785'  => 'Skawina Rzepnik',
  'b3441' => 'Skawina SCK',
  'b2480' => 'Skawina Samborek Most',
  'b1134' => 'Skawina Starostwo Powiatowe',
  'b1007' => 'Skawina Szkoła',
  'b1008' => 'Skawina Sąd',
  'b2479' => 'Skawina Tyniecka',
  'b2478' => 'Skawina Tyniecka Osiedle',
  'b3173' => 'Skawina Tyniecka Rzepnik (nż)',
  'b1011' => 'Skawina Wojska Polskiego',
  'b1100' => 'Skawina Wyspiańskiego',
  'b2820' => 'Skawina Wyspiańskiego Szkoła (nż)',
  'b1105' => 'Skawina Zachodnia (nż)',
  'b3334' => 'Skawina Żwirowa (nż)',
  'b3335' => 'Skawina Żwirownia (nż)',
# 'b3740' => 'Skała (nż)', # nowa nazwa # 'b3792' => 'Skała Rzeplińska (nż)',
  'b219'  => 'Skała Kmity (nż)',
  'b3739' => 'Skała Rynek',
  'b3792' => 'Skała Rzeplińska (nż)',
  'b3741' => 'Skała Wieś (nż)',
  'b766'  => 'Skotniki',
  'b3181' => 'Skotniki Kościół',
  'b604'  => 'Skotniki Szkoła',
  'b752'  => 'Skośna',
  'b42'   => 'Skrajna (nż)',
# 'b953'  => 'Skrzeszowice', # nowa nazwa # 'b3286' => 'Skrzeszowice OSP Boisko',
  'b3286' => 'Skrzeszowice OSP Boisko',
# 'b967'  => 'Skrzyżowanie do Podchruścia (nż)', # nowa nazwa # 'b3543' => 'Modlnica Podchruście (nż)',
# 'b1153' => 'Smardzowice', # nowa nazwa # 'b3454' => 'Smardzowice Remiza',
  'b3747' => 'Smardzowice Kościelna (nż)',
  'b3746' => 'Smardzowice Podgóry (nż)',
  'b3454' => 'Smardzowice Remiza',
  'b2972' => 'Smardzowice Wołówka (nż)',
  'b816'  => 'Smoleńskiego',
  'b572'  => 'Smolki',
  'b699'  => 'Soboniowice',
  'b746'  => 'Solvay',
  'b3728' => 'Sosabowskiego',
  'b2544' => 'Sołtysowska (nż)',
  'b2546' => 'Sołtysowska Osiedle',
  'b2545' => 'Sołtysowska Zakłady',
  'b116'  => 'Spadochroniarzy',
  'b3276' => 'Spławy',
  'b57'   => 'Stachiewicza',
  'b1308' => 'Staniątki Wiadukt (nż)',
  'b144'  => 'Stara Wola',
  'b2558' => 'Stare Wiślisko',
  'b3460' => 'Starego Wiarusa',
  'b358'  => 'Starowiślna',
  'b3032' => 'Stary Kleparz',
  'b2791' => 'Stawowa',
  'b112'  => 'Stella-Sawickiego',
  'b558'  => 'Stoczniowców',
  'b711'  => 'Stojałowskiego',
  'b359'  => 'Stradom',
  'b423'  => 'Struga',
  'b2874' => 'Strycharska',
  'b101'  => 'Strzelców',
  'b141'  => 'Strzelnica',
  'b618'  => 'Sucha',
  'b666'  => 'Sucharskiego (nż)',
  'b456'  => 'Suchy Jar (nż)',
  'b2602' => 'Sudolska',
  'b476'  => 'Sulechów (nż)',
  'b2570' => 'Surzyckiego',
  'b2571' => 'Sułkowskiego',
# 'b2497' => 'Sułków (nż)', # nowa nazwa # 'b3799' => 'Sułków Zbój (nż)',
  'b3799' => 'Sułków Zbój (nż)',
  'b739'  => 'Swoszowice Autostrada (nż)',
  'b732'  => 'Swoszowice Poczta',
  'b3644' => 'Swoszowice SKA',
  'b3129' => 'Swoszowice Szkoła',
  'b869'  => 'Szafrańska',
  'b562'  => 'Szczecińska',
  'b2593' => 'Szczegów',
  'b220'  => 'Szczyglice',
  'b3045' => 'Szczyglice Autostrada',
  'b871'  => 'Szczyglice Dom Kultury',
  'b224'  => 'Szczyglice Most (nż)',
# 'b2910' => 'Szczyglice Podkamycze', # nowa nazwa # 'b3487' => 'Rząska Podkamycze',
  'b3691' => 'Szlifierska (nż)',
  'b651'  => 'Szparagowa',
  'b3203' => 'Szpital Jana Pawła II',
  'b3036' => 'Szpital Narutowicza',
  'b2759' => 'Szpital Okulistyczny',
  'b827'  => 'Szpital Rydygiera',
  'b3383' => 'Szpital Uniwersytecki / Instytut Pediatrii',  # poprawione # 'b3383' => 'Szpital Uniwersytecki / Instytut Pediatr',
  'b425'  => 'Szpital Żeromskiego',
  'b575'  => 'Szwedzka',
# 'b971'  => 'Szyce I (nż)', # nowa nazwa # 'b3547' => 'Szyce Wesoła (nż)',
# 'b970'  => 'Szyce II (nż)', # nowa nazwa # 'b3546' => 'Szyce Spacerowa (nż)',
  'b3546' => 'Szyce Spacerowa (nż)',
  'b3547' => 'Szyce Wesoła (nż)',
  'b2646' => 'Szymańskiego (nż)',
  'b628'  => 'Sławka (nż)',
# 'b2607' => 'Słomczyńskiego', # nowa nazwa # 'b3726' => 'Kuźnicy Kołłątajowskiej',
  'b577'  => 'Słomiana',
  'b2733' => 'Słomniki Kościuszki (nż)',
  'b1315' => 'Słomniki Osiedle',
  'b1316' => 'Słomniki Rynek',
  'b1317' => 'Słomniki Zagłoby (nż)',
  'b2584' => 'Słona Woda',
  'b3138' => 'Słoneckiego',
# 'b314'  => 'Słonecznikowa', # nowa nazwa # 'b3465' => 'Owcy-Orwicza',
# 'b3293' => 'Słowiańska', # tymczasowy - przebudowa linii do Bronowic
  'b2872' => 'TAURON Arena Kraków',
# 'b2871' => 'TAURON Arena Kraków Al. Pokoju (nż)', # nowa nazwa # 'b3473' => 'TAURON Arena Kraków al. Pokoju',
  'b3040' => 'TAURON Arena Kraków Wieczysta',
  'b3473' => 'TAURON Arena Kraków al. Pokoju',
  'b2724' => 'TR',
  'b3172' => 'Taklińskiego (nż)',
  'b77'   => 'Teatr Bagatela',
  'b420'  => 'Teatr Ludowy',
  'b3242' => 'Teatr Słowackiego',
  'b681'  => 'Teligi',
  'b919'  => 'Tischnera',
# 'b3218' => 'Tomaszkowice', # nowa nazwa # 'b3801' => 'Tomaszkowice Urząd Gminy Biskupice',
  'b3801' => 'Tomaszkowice Urząd Gminy Biskupice',
# 'b989'  => 'Tomaszowice', # nowa nazwa # 'b3557' => 'Tomaszowice Dwór',
  'b3557' => 'Tomaszowice Dwór',
# 'b2697' => 'Tomaszowice Gliniki (nż)', # nowa nazwa # 'b3558' => 'Tomaszowice Spacerowa (nż)',
# 'b988'  => 'Tomaszowice I (nż)', # nowa nazwa # 'b3556' => 'Tomaszowice Zacisze (nż)',
  'b3167' => 'Tomaszowice Kolberga (nż)',
  'b3558' => 'Tomaszowice Spacerowa (nż)',
# 'b987'  => 'Tomaszowice Wedonka (nż)', # nowa nazwa # 'b3555' => 'Modlnica Kościelna (nż)',
  'b3556' => 'Tomaszowice Zacisze (nż)',
  'b139'  => 'Tondosa (nż)',
  'b21'   => 'Tonie',
  'b990'  => 'Tonie Gliniki (nż)',
  'b25'   => 'Tonie Kąty (nż)',
  'b23'   => 'Tonie Skrzyżowanie',
  'b966'  => 'Tor Kajakowy',
  'b936'  => 'Torfowa',
# 'b3450' => 'Tretówka', # tymczasowy - przebudowa ul. Wrony
# 'b994'  => 'Trojadyn Skrzyżowanie (nż)', # nowa nazwa # 'b3496' => 'Giebułtów Świętego Idziego (nż)',
# 'b184'  => 'Trojanowice', # nowa nazwa # 'b3788' => 'Trojanowice Słoneczna',
  'b2977' => 'Trojanowice Krakowska (nż)',
  'b178'  => 'Trojanowice Pętla',
  'b183'  => 'Trojanowice Strugi (nż)',
  'b3788' => 'Trojanowice Słoneczna',
  'b2650' => 'Truskawkowa (nż)',
# 'b2720' => 'Trzecia Góra (nż)', # nowa nazwa # 'b3341' => 'Węgrzce Trzecia Góra (nż)',
# 'b3222' => 'Trąbki I (nż)', # nowa nazwa # 'b3805' => 'Trąbki Pacówki (nż)',
# 'b3223' => 'Trąbki OSP', # nowa nazwa # 'b3806' => 'Trąbki Remiza',
  'b3245' => 'Trąbki P+R',
  'b3805' => 'Trąbki Pacówki (nż)',
  'b3806' => 'Trąbki Remiza',
  'b714'  => 'Tuchowska',
  'b3647' => 'Turowicza',
# 'b999'  => 'Turowicza (nż)', # nowa nazwa # 'b3648' => 'Połomskiego (nż)',
  'b3683' => 'Tymiankowa (nż)',
  'b593'  => 'Tyniec',
  'b591'  => 'Tyniec Kamieniołom',
  'b2562' => 'Tyniecka Autostrada (nż)',
  'b3736' => 'UJ / AST',
  'b3808' => 'UKEN',
# 'b3140' => 'UR Aleja 29 Listopada', # nowa nazwa # 'b3469' => 'UR al. 29 Listopada',
  'b5'    => 'UR Balicka',
  'b3469' => 'UR al. 29 Listopada',
  'b115'  => 'Ugorek',
  'b1017' => 'Ujazd Pętla',
  'b723'  => 'Ukraina (nż)',
  'b127'  => 'Uniwersytet Ekonomiczny',
# 'b321'  => 'Uniwersytet Jagielloński', # nowa nazwa # 'b3736' => 'UJ / AST',
# 'b88'   => 'Uniwersytet Pedagogiczny', # nowa nazwa # 'b3808' => 'UKEN',
  'b67'   => 'Urząd Marszałkowski',
  'b957'  => 'Urząd Skarbowy Nowa Huta',
  'b83'   => 'Urzędnicza',
  'b3787' => 'Vetulaniego',
  'b486'  => 'Wadowska (nż)',
  'b485'  => 'Wadów',
  'b492'  => 'Wadów Działki (nż)',
  'b2554' => 'Wadów Glinik (nż)',
  'b3501' => 'Wadów Os. Kolejowe',
# 'b2738' => 'Wadów Os.Kolejowe', # nowa nazwa # 'b3501' => 'Wadów Os. Kolejowe',
  'b483'  => 'Wadów Osiedle (nż)',
  'b484'  => 'Wadów Szkoła',
  'b463'  => 'Walcownia',
  'b2599' => 'Warchałowskiego',
# 'b3264' => 'Warmijska', # tymczasowy - przebudowa linii do Bronowic
  'b3131' => 'Warszewicza (nż)',
# 'b338'  => 'Warszówka (nż)', # nowa nazwa # 'b3347' => 'Michałowice Warszawka (nż)',
  'b2564' => 'Wały Wiślane (nż)',
  'b2543' => 'Wańkowicza',
  'b2639' => 'Ważewskiego',
  'b2578' => 'Weigla',
  'b133'  => 'Wesele',
  'b434'  => 'Wiadukty (nż)',
  'b3382' => 'Widłakowa (nż)',
  'b2722' => 'Wielicka Granica Miasta',
  'b3380' => 'Wieliczka Centrum',
  'b898'  => 'Wieliczka Cmentarz',
  'b3632' => 'Wieliczka Czarnochowska Cmentarz (nż)',
# 'b3246' => 'Wieliczka Gdowska', # nowa nazwa # 'b3214' => 'Wieliczka Ochronka',
  'b2852' => 'Wieliczka Goliana',
# 'b2862' => 'Wieliczka Kampus', # nowa nazwa # 'b3429' => 'Wieliczka Miasto',
  'b3430' => 'Wieliczka Klasztor',
  'b2814' => 'Wieliczka Klaśnieńska (nż)',
  'b1167' => 'Wieliczka Kopalnia Soli',
# 'b911'  => 'Wieliczka Kościół', # nowa nazwa # 'b3430' => 'Wieliczka Klasztor',
  'b3653' => 'Wieliczka Krzyszkowice Dom Ludowy',
  'b3650' => 'Wieliczka Krzyszkowice Kościół (nż)',
  'b3431' => 'Wieliczka Mediateka',
  'b3429' => 'Wieliczka Miasto',
  'b3651' => 'Wieliczka Modrzewiowa (nż)',
# 'b2730' => 'Wieliczka Niepołomska (nż)', # nowa nazwa # 'b3566' => 'Wieliczka Niepołomska Granica (nż)',
  'b3566' => 'Wieliczka Niepołomska Granica (nż)',
  'b3214' => 'Wieliczka Ochronka',
  'b3630' => 'Wieliczka Orzechowa (nż)',
# 'b3006' => 'Wieliczka Os.Asnyka', # nowa nazwa # 'b3504' => 'Wieliczka Os. Asnyka',
  'b3504' => 'Wieliczka Os. Asnyka',
  'b3649' => 'Wieliczka Os. Szymanowskiego (nż)',
  'b2503' => 'Wieliczka Park',
  'b3247' => 'Wieliczka Polna (nż)',
# 'b1168' => 'Wieliczka Rynek', # nowa nazwa # 'b3431' => 'Wieliczka Mediateka',
  'b3652' => 'Wieliczka Różana (nż)',
  'b2816' => 'Wieliczka Solne Miasto',
  'b3235' => 'Wieliczka Stacja Paliw',
  'b2815' => 'Wieliczka Sąd',
  'b3633' => 'Wieliczka Wygoda Kapliczka (nż)',
  'b3631' => 'Wieliczka Zbożowa (nż)',
# 'b972'  => 'Wielka Wieś (nż)', # nowa nazwa # 'b3548' => 'Wielka Wieś Szkoła (nż)',
  'b3548' => 'Wielka Wieś Szkoła (nż)',
# 'b1364' => 'Wielkie Drogi (nż)', # nowa nazwa # 'b3536' => 'Facimiech Pod Kolebą (nż)',
  'b1232' => 'Wielkie Drogi Ośrodek Zdrowia (nż)',
  'b1113' => 'Wielkie Drogi PKP (nż)',
  'b1233' => 'Wielkie Drogi Szkoła (nż)',
  'b1112' => 'Wielkie Drogi Trzebol (nż)',
  'b3564' => 'Wierzyńskiego',
  'b866'  => 'Wiklinowa (nż)',
  'b1267' => 'Wiktorowice Centrum (nż)',
  'b1264' => 'Wiktorowice Granica (nż)',
  'b3189' => 'Wiktorowice Rozlewnia Wód (nż)',
  'b1266' => 'Wiktorowice Skrzyżowanie (nż)',
  'b2515' => 'Wileńska',
  'b737'  => 'Wilga (nż)',
  'b1372' => 'Winnicka (nż)',
  'b29'   => 'Witkowice',
  'b30'   => 'Witkowice Nowe',
  'b3783' => 'Witkowicka',
  'b718'  => 'Witosa',
# 'b1025' => 'Więckowice (nż)', # nowa nazwa # 'b3416' => 'Więckowice Ogrodowa (nż)',
  'b2921' => 'Więckowice Lipka (nż)',
  'b3416' => 'Więckowice Ogrodowa (nż)',
# 'b348'  => 'Więcławice Stare (nż)', # nowa nazwa # 'b3372' => 'Więcławice Stare Centrum (nż)',
  'b3372' => 'Więcławice Stare Centrum (nż)',
  'b2987' => 'Więcławice Stare Wysyłek (nż)',
  'b110'  => 'Wiślicka',
  'b634'  => 'Wlotowa',
  'b263'  => 'Wodociągi (nż)',
  'b3115' => 'Wodociągowa (nż)',
  'b1284' => 'Wola Batorska Borek (nż)',
  'b1283' => 'Wola Batorska Cmentarz (nż)',
  'b1282' => 'Wola Batorska Kościół (nż)',
  'b1285' => 'Wola Batorska Mikoniowiec (nż)',
  'b1280' => 'Wola Batorska Ruskie (nż)',
  'b1286' => 'Wola Batorska Zamoglice (nż)',
  'b1281' => 'Wola Batorska Żwirownia (nż)',
  'b629'  => 'Wola Duchacka',
# 'b949'  => 'Wola Luborzycka (nż)', # nowa nazwa # 'b3284' => 'Wola Luborzycka Skrzyżowanie (nż)',
  'b1332' => 'Wola Luborzycka Działki (nż)',
  'b950'  => 'Wola Luborzycka Las (nż)',
  'b3284' => 'Wola Luborzycka Skrzyżowanie (nż)',
# 'b1128' => 'Wola Radziszowska', # nowa nazwa # 'b3330' => 'Wola Radziszowska Pętla',
  'b1127' => 'Wola Radziszowska Centrum',
  'b1129' => 'Wola Radziszowska Chorzyny (nż)',
# 'b3185' => 'Wola Radziszowska Kapelanka (nż)', # nowa nazwa # 'b3362' => 'Wola Radziszowska Kapelanka (nż)',
  'b3362' => 'Wola Radziszowska Kapelanka (nż)',
  'b1126' => 'Wola Radziszowska Lipki (nż)',
  'b1124' => 'Wola Radziszowska Mała Ostra Góra (nż)',
  'b1125' => 'Wola Radziszowska Most (nż)',
  'b1336' => 'Wola Radziszowska Podgaźle (nż)',
  'b3330' => 'Wola Radziszowska Pętla',
# 'b1337' => 'Wola Radziszowska Łęg (nż)', # dawny
  'b1291' => 'Wola Zabierzowska (nż)',
# 'b172'  => 'Wola Zachariaszowska', # nowa nazwa # 'b3343' => 'Wola Zachariaszowska Szkoła',
# 'b2702' => 'Wola Zachariaszowska Kresy', # nowa nazwa # 'b3356' => 'Michałowice Las Michałowski',
  'b3343' => 'Wola Zachariaszowska Szkoła',
  'b3360' => 'Wola Zachariaszowska Słoneczna',
# 'b2976' => 'Wola Zachariaszowska Zakońce', # nowa nazwa # 'b3360' => 'Wola Zachariaszowska Słoneczna',
# 'b539'  => 'Wolica (nż)', # nowa nazwa # 'b3687' => 'Ks. Luzara (nż)',
  'b538'  => 'Wolica Kościół (nż)',
# 'b537'  => 'Wolica Las', # nowa nazwa # 'b3686' => 'Betonowa',
  'b536'  => 'Wolica Most',
# 'b540'  => 'Wolica Sklep (nż)', # nowa nazwa # 'b3427' => 'Wolica Szkoła (nż)',
  'b3427' => 'Wolica Szkoła (nż)',
# 'b894'  => 'Wołowice (nż)', # nowa nazwa # 'b3397' => 'Wołowice Remiza (nż)',
  'b3231' => 'Wołowice Grotowa (nż)',
  'b3227' => 'Wołowice Grotowa Skrzyżowanie (nż)',
  'b909'  => 'Wołowice Kapliczka',
# 'b1207' => 'Wołowice Niwa (nż)', # nowa nazwa # 'b3403' => 'Wołowice Niwka (nż)',
  'b3403' => 'Wołowice Niwka (nż)',
  'b2907' => 'Wołowice Pichonówka (nż)',
  'b3397' => 'Wołowice Remiza (nż)',
  'b1205' => 'Wołowice Sklep (nż)',
  'b3401' => 'Wołowice Skrzyżowanie (nż)',
  'b893'  => 'Wołowice Szkoła',
  'b3229' => 'Wołowice Zawierzbie (nż)',
  'b643'  => 'Wrobela',
  'b68'   => 'Wrocławska',
  'b2598' => 'Wrony',
# 'b2948' => 'Wrząsowice (nż)', # nowa nazwa # 'b3319' => 'Wrząsowice Bonifraterska (nż)',
  'b3426' => 'Wrząsowice Bonifraterska (nż)',
# 'b3319' => 'Wrząsowice Bonifraterska  (nż)', # nowa nazwa # 'b3426' => 'Wrząsowice Bonifraterska (nż)',
  'b2946' => 'Wrząsowice Centrum',
  'b1234' => 'Wrząsowice Kowaleca (nż)',
  'b2950' => 'Wrząsowice Nad Wilgą',
  'b2947' => 'Wrząsowice Pileckiego (nż)',
  'b2952' => 'Wrząsowice Pod Skałą (nż)',
# 'b3212' => 'Wrząsowice Rondo', # tymczasowy - przebudowa ul. Myślenickiej
  'b3197' => 'Wrząsowice Spacerowa (nż)',
  'b2945' => 'Wrząsowice Wrzosowa (nż)',
  'b2944' => 'Wrząsowice Zielona (nż)',
  'b3148' => 'Wróblowice',
  'b729'  => 'Wróblowice Szkoła',
  'b499'  => 'Wróżenice',
  'b2641' => 'Wróżenice Górka (nż)',
  'b2640' => 'Wróżenicka (nż)',
  'b60'   => 'Wybickiego',
# 'b2647' => 'Wyciąska (nż)', # nowa nazwa # 'b3683' => 'Tymiankowa (nż)',
  'b3678' => 'Wyciąska (nż)',
# 'b508'  => 'Wyciąże (nż)', # nowa nazwa # 'b3678' => 'Wyciąska (nż)',
  'b3677' => 'Wyciąże Północ (nż)',
  'b515'  => 'Wyciąże Sklep (nż)',
# 'b521'  => 'Wyciąże Wiadukt (nż)', # nowa nazwa # 'b3684' => 'Czeczeńska (nż)',
# 'b2645' => 'Wyciąże Zachód (nż)', # nowa nazwa # 'b3677' => 'Wyciąże Północ (nż)',
  'b683'  => 'Wydział Farmaceutyczny UJ',
  'b43'   => 'Wyki',
  'b2998' => 'Wysiołek Luborzycki (nż)',
  'b2999' => 'Wysiołek Luborzycki Kapkazy (nż)',
  'b1320' => 'Wysiołek Luborzycki Radwany (nż)',
  'b2997' => 'Wysiołek Luborzycki Skrzyżowanie (nż)',
  'b1259' => 'Wysłouchów',
# 'b292'  => 'Wyźrał Szkoła (nż)', # nowa nazwa # 'b3303' => 'Kaszów Szkoła nr 2 (nż)',
# 'b293'  => 'Wyźrał Wielka Droga (nż)', # nowa nazwa # 'b3304' => 'Kaszów Wielka Droga (nż)',
  'b442'  => 'Wzgórza Krzesławickie',
  'b3532' => 'Węglarska',
# 'b328'  => 'Węgrzce', # nowa nazwa # 'b3592' => 'Węgrzce A1',
  'b3592' => 'Węgrzce A1',
  'b3442' => 'Węgrzce B1 (nż)',
  'b3443' => 'Węgrzce B4 (nż)',
# 'b2980' => 'Węgrzce Bosutów (nż)', # nowa nazwa # 'b3444' => 'Węgrzce Sudół (nż)',
# 'b2979' => 'Węgrzce Bosutów Sudół (nż)', # nowa nazwa # 'b3443' => 'Węgrzce B4 (nż)',
  'b1079' => 'Węgrzce Błonie',
  'b165'  => 'Węgrzce Centrum',
  'b1074' => 'Węgrzce Centrum Medyczne (nż)',
  'b1073' => 'Węgrzce Magiczne Wzgórze (nż)',
  'b1080' => 'Węgrzce Pętla',
  'b327'  => 'Węgrzce Starostwo Powiatowe',
  'b3444' => 'Węgrzce Sudół (nż)',
# 'b3341' => 'Węgrzce Trzecia Góra (nż)', # zlikwidowany
  'b3786' => 'Węgrzce Warszawska (nż)',
  'b3580' => 'Węgrzce Wielkie Gościniec (nż)',
# 'b1163' => 'Węgrzce Wielkie II (nż)', # nowa nazwa # 'b3580' => 'Węgrzce Wielkie Gościniec (nż)',
# 'b1161' => 'Węgrzce Wielkie III (nż)', # nowa nazwa # 'b3579' => 'Węgrzce Wielkie OSP (nż)',
  'b3579' => 'Węgrzce Wielkie OSP (nż)',
  'b3270' => 'Węgrzce Wielkie Pętla',
  'b487'  => 'Węgrzynowice',
  'b488'  => 'Węgrzynowice Centrum (nż)',
  'b2552' => 'Węgrzynowice Dół (nż)',
  'b3277' => 'Węgrzynowicka (nż)',
  'b3127' => 'Węzeł Wielicki (nż)',
  'b3118' => 'Władysława Jagiełły',
  'b3110' => 'Władysława Łokietka',
# 'b807'  => 'Włosań', # nowa nazwa # 'b3314' => 'Włosań Centrum',
  'b3314' => 'Włosań Centrum',
  'b3053' => 'Włosań Dział Wschodni (nż)',
  'b809'  => 'Włosań Kopań (nż)',
  'b808'  => 'Włosań Krzyżówka (nż)',
  'b146'  => 'ZOO',
# 'b2495' => 'Zabawa (nż)', # nowa nazwa # 'b3797' => 'Zabawa Centrum (nż)',
  'b3797' => 'Zabawa Centrum (nż)',
  'b3567' => 'Zabawa Granica (nż)',
# 'b2510' => 'Zabawa I (nż)', # nowa nazwa # 'b3567' => 'Zabawa Granica (nż)',
# 'b199'  => 'Zabierzów', # nowa nazwa # 'b3513' => 'Zabierzów Kmity',
  'b1287' => 'Zabierzów Bocheński Centrum (nż)',
  'b3515' => 'Zabierzów Centrum',
# 'b198'  => 'Zabierzów Działki (nż)', # nowa nazwa # 'b3512' => 'Zabierzów Rzemieślnicza (nż)',
  'b3248' => 'Zabierzów Eximius Park',
# 'b202'  => 'Zabierzów I', # nowa nazwa # 'b3516' => 'Zabierzów Kamieniołom',
  'b3516' => 'Zabierzów Kamieniołom',
  'b3513' => 'Zabierzów Kmity',
  'b961'  => 'Zabierzów Młyn',
  'b213'  => 'Zabierzów Ośrodek Zdrowia',
  'b204'  => 'Zabierzów PKP',
  'b203'  => 'Zabierzów Piaski (nż)',
# 'b201'  => 'Zabierzów Piekarnia', # nowa nazwa # 'b3515' => 'Zabierzów Centrum',
  'b3249' => 'Zabierzów Rynek',
  'b3512' => 'Zabierzów Rzemieślnicza (nż)',
# 'b200'  => 'Zabierzów Sklep', # nowa nazwa # 'b3514' => 'Zabierzów Willowa',
  'b3514' => 'Zabierzów Willowa',
  'b3517' => 'Zabierzów Wrzosowa (nż)',
  'b503'  => 'Zabłocie Kościelnickie (nż)',
  'b590'  => 'Zachodnia',
# 'b2888' => 'Zagacie (nż)', # nowa nazwa # 'b3305' => 'Zagacie Górka (nż)',
  'b3305' => 'Zagacie Górka (nż)',
  'b2889' => 'Zagacie Witkówki (nż)',
  'b3499' => 'Zagaje (nż)',
# 'b916'  => 'Zagórzyce Dworskie', # nowa nazwa # 'b3375' => 'Zagórzyce Dworskie Remiza',
  'b3375' => 'Zagórzyce Dworskie Remiza',
# 'b917'  => 'Zagórzyce Stare (nż)', # nowa nazwa # 'b3376' => 'Zagórzyce Stare Owocowa (nż)',
  'b3376' => 'Zagórzyce Stare Owocowa (nż)',
  'b397'  => 'Zajezdnia Bieńczyce',
  'b465'  => 'Zajezdnia Nowa Huta',
  'b2576' => 'Zajezdnia Płaszów',
  'b1254' => 'Zajezdnia Wola Duchacka',
  'b155'  => 'Zakamycze',
  'b3179' => 'Zakarnie (nż)',
  'b7'    => 'Zakliki (nż)',
  'b2789' => 'Zakole',
# 'b1305' => 'Zakrzów (nż)', # nowa nazwa # 'b3795' => 'Zakrzów Ogrodzieniec (nż)',
  'b3795' => 'Zakrzów Ogrodzieniec (nż)',
  'b2649' => 'Zakępie (nż)',
# 'b511'  => 'Zakład Przeróbki (nż)', # nowa nazwa # 'b3680' => 'Brama nr 8 (nż)',
  'b137'  => 'Zarzecze',
  'b274'  => 'Zaskale (nż)',
# 'b356'  => 'Zastów', # nowa nazwa # 'b3453' => 'Zastów Pętla',
  'b1265' => 'Zastów Działki (nż)',
  'b3453' => 'Zastów Pętla',
  'b839'  => 'Zatyka (nż)',
  'b755'  => 'Zawiszy',
  'b751'  => 'Zawiła (nż)',
  'b3721' => 'Zawodzie',
  'b721'  => 'Zbydniowice',
  'b3147' => 'Zbydniowicka',
  'b3538' => 'Zelczyna (nż)',
# 'b1116' => 'Zelczyna I (nż)', # nowa nazwa # 'b3538' => 'Zelczyna (nż)',
  'b3537' => 'Zelczyna PKP',
  'b3716' => 'Zelczyna Piaski (nż)',
# 'b1115' => 'Zelczyna Sklep', # nowa nazwa # 'b3537' => 'Zelczyna PKP',
  'b1170' => 'Zelczyna Szkoła (nż)',
  'b3200' => 'Zelków Kościuszki (nż)',
  'b3198' => 'Zelków Pętla',
  'b2918' => 'Zelków Spławy (nż)',
  'b210'  => 'Zelków Staw',
  'b209'  => 'Zelków Wola (nż)',
  'b447'  => 'Zesławice',
  'b2621' => 'Zesławice Ogródki Działkowe (nż)',
  'b581'  => 'Zielińskiego (nż)',
  'b3573' => 'Zielonki Długopolska',
  'b2784' => 'Zielonki Galicyjska (nż)',
  'b3358' => 'Zielonki Jaskinia Zielonkowska (nż)',
  'b2978' => 'Zielonki Marszowiec Pętla',
  'b3574' => 'Zielonki Na Popielówkę',
  'b177'  => 'Zielonki Rozjazd',
  'b182'  => 'Zielonki Skrzyżowanie',
  'b3576' => 'Zielonki Słoneczna',
  'b180'  => 'Zielonki Transformator',
# 'b181'  => 'Zielonki UG', # nowa nazwa # 'b3492' => 'Zielonki Urząd Gminy',
  'b3492' => 'Zielonki Urząd Gminy',
  'b149'  => 'Zielony Dół',
  'b2577' => 'Złocieniowa',
  'b811'  => 'Złocień',
  'b679'  => 'Ćwiklińskiej',
  'b922'  => 'Łagiewniki',
  'b3643' => 'Łagiewniki SKA',
  'b563'  => 'Łanowa',
  'b3069' => 'Łobzów SKA',
# 'b951'  => 'Łososkowice', # nowa nazwa # 'b3285' => 'Łososkowice Remiza',
  'b3285' => 'Łososkowice Remiza',
  'b952'  => 'Łososkowice Szkoła (nż)',
  'b480'  => 'Łuczanowice',
  'b482'  => 'Łuczanowice Skrzyżowanie',
  'b3066' => 'Łuczanowicka (nż)',
# 'b1121' => 'Łuczyce', # nowa nazwa # 'b3287' => 'Łuczyce Kosynierów',
  'b3287' => 'Łuczyce Kosynierów',
  'b1120' => 'Łuczyce Las (nż)',
  'b1231' => 'Łuczyce Zjawienie (nż)',
  'b2761' => 'Łuczyce Zwierzyniec (nż)',
  'b2604' => 'Łuczyńskiego (nż)',
  'b120'  => 'Łukasiewicza',
  'b640'  => 'Łutnia',
  'b2596' => 'Łużycka (nż)',
  'b384'  => 'Łęczycka',
# 'b301'  => 'Ściejowice Granica (nż)', # nowa nazwa # 'b3395' => 'Rączna Bażanty (nż)',
  'b3226' => 'Ściejowice Kościel (nż)',
  'b1246' => 'Ściejowice Na Bagnach (nż)',
  'b3225' => 'Ściejowice Remiza (nż)',
  'b2610' => 'Ślaskiego (nż)',
  'b1374' => 'Śliwiaka (nż)',
  'b2517' => 'Śliwiaka Zakłady',
  'b903'  => 'Ślósarczyka',
# 'b2742' => 'Św.Wawrzyńca', # nowa nazwa # 'b3471' => 'św. Wawrzyńca',
  'b2605' => 'Świdzińskiego (nż)',
# 'b2942' => 'Świątniki Bielowicza Szkoła', # nowa nazwa # 'b3316' => 'Świątniki Górne Bielowicza Szkoła',
# 'b2949' => 'Świątniki Buk (nż)', # nowa nazwa # 'b3320' => 'Świątniki Górne Buk (nż)',
# 'b847'  => 'Świątniki Centrum', # nowa nazwa # 'b3317' => 'Świątniki Górne Centrum',
  'b3316' => 'Świątniki Górne Bielowicza Szkoła',
  'b3320' => 'Świątniki Górne Buk (nż)',
  'b3317' => 'Świątniki Górne Centrum',
  'b3325' => 'Świątniki Górne Krakowska (nż)',
  'b3051' => 'Świątniki Górne Piasna Górka (nż)',
  'b3315' => 'Świątniki Górne Skrzyżowanie (nż)',
  'b3318' => 'Świątniki Górne Urząd Miasta i Gminy',
# 'b2768' => 'Świątniki Krakowska (nż)', # nowa nazwa # 'b3325' => 'Świątniki Górne Krakowska (nż)',
# 'b845'  => 'Świątniki Skrzyżowanie (nż)', # nowa nazwa # 'b3315' => 'Świątniki Górne Skrzyżowanie (nż)',
# 'b2943' => 'Świątniki Urząd Miasta i Gminy', # nowa nazwa # 'b3318' => 'Świątniki Górne Urząd Miasta i Gminy',
  'b3471' => 'św. Wawrzyńca',
  'b2592' => 'Żelazowskiego (nż)',
# 'b343'  => 'Żerkowice Kolonia (nż)', # nowa nazwa # 'b3349' => 'Narama Księża (nż)',
# 'b344'  => 'Żerkowice Skrzyżowanie (nż)', # nowa nazwa # 'b3350' => 'Krasieniec Stary Skrzyżowanie (nż)',
  'b417'  => 'Żeromskiego',
# 'b534'  => 'Żwirownia', # nowa nazwa # 'b3542' => 'Przylasek Rusiecki Kąpielisko',
  'b748'  => 'Żywiecka',
  'b834'  => 'Żyzna (nż)',
);
